(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1920,
	height: 1080,
	fps: 60,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.step = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#315175").s().p("ApCCUIAAknISFAAIAAEng");
	this.shape.setTransform(57.9,14.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,115.9,29.7);


(lib.diploma = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D7D1C2").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAAAIAAAAg");
	this.shape.setTransform(47.5,86.1,0.999,0.999,-120);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BDAEA1").s().p("AhnAyIgIgBIgPABQgFgBgKABIgBgBIACAAIAagEQADAAAEgDQAGgEADgGIAJgMIAJgTIAFgOIALgjQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIgNAuQgCAFgFAKIgJAQIgLANIgEAEQABACADAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQALAAAEgFIAMgOIAFgIIAFgKIAJgbIADgLIADgIIABAAQAAABgBAEIgHAZQgDAIgIARQgGALgHAIIgHAHIgCADIAGAAIAKAAIBJgBIAPAAIAHgBIALABIBBAAQABAAABAAQAAAAABAAQAAAAABAAQAAAAABAAIAJAAIAWABIAHAAIgDABIjvADg");
	this.shape_1.setTransform(50.6,80.3,0.999,0.999,-120);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C9C1B3").s().p("AACADIgEgFIACgBIAAACIACADIAAACg");
	this.shape_2.setTransform(18.8,4,0.999,0.999,-120);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#D7D1C2").s().p("AACADQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIAAAAIgEgGQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIAEAAIAAABIACAFQADABAAAIIgBAAg");
	this.shape_3.setTransform(19,3.5,0.999,0.999,-120);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#C9C1B3").s().p("ACmAQIg6gGIgTgDIjRgTIgKAAIgDgBIgGAAIgVgBQgBAAgBABQgBAAAAAAQgBAAAAABQAAAAAAABIgBgBIgBgBIgBgBQAAAAABgBQAAAAAAAAQABAAAAAAQAAgBABAAIAIAAIAEAAIAOAAIAHACIADgBIARABIAMABIACAAIAOABIAGAAIABAAQACABAGAAIAAAAIAtAEIAPACIAaADIAFAAIAGABIAIABIAFAAIABAAIAQAAIAdAFIAUACIA4AFIAAgDIgBgDQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQADAFAAACIgBACIAAABIgBgBg");
	this.shape_4.setTransform(26.6,17.9,0.999,0.999,-120);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#91091E").s().p("AAAAAIABAAIgBABg");
	this.shape_5.setTransform(32,42.1,0.999,0.999,-120);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#91091E").s().p("AAAAAIgBAAIABAAIACABIgCgBg");
	this.shape_6.setTransform(45.8,41.5,0.999,0.999,-120);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#91091E").s().p("AAAAAIABAAIAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_7.setTransform(44.8,41.4,0.999,0.999,-120);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#91091E").s().p("AgBAAIABAAIAAAAIACAAIgBABg");
	this.shape_8.setTransform(45.2,41.5,0.999,0.999,-120);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E3DED2").s().p("AgBAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIACAAIgBAAg");
	this.shape_9.setTransform(29.4,24.1,0.999,0.999,-120);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E3DED2").s().p("AgBAAIgBAAQACAAADAAIgBAAg");
	this.shape_10.setTransform(24.6,13.3,0.999,0.999,-120);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E3DED2").s().p("AgFAAQABAAAAAAQAAAAAAAAQABAAAAAAQABAAAAAAIAHAAIgBAAIgJAAg");
	this.shape_11.setTransform(25,14.3,0.999,0.999,-120);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E3DED2").s().p("AgKAAIADgBIASACIgBABg");
	this.shape_12.setTransform(26.1,16.6,0.999,0.999,-120);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E3DED2").s().p("AAMAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIgDAAIgLAAIgeAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQAAAAgBAAIgDAAQAAgBAAAAQABAAAAAAQAAAAABAAQAAAAABAAIAVAAIAOAAIAGABIAtABIgEABg");
	this.shape_13.setTransform(31.7,28.5,0.999,0.999,-120);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#D7D1C2").s().p("ACaAPIgPgBIhWgLIgBABIgBgBIgHAAIgBgBIgIAAIgEABIgDgBIgBAAIgDgBIgVgBIgDAAIgCgBIgPgBIgMgBIgJgBIgDAAIgEgBIgBAAIgDAAIgBgBIgOgBIgBAAQgEgBgCABIgBgBIgLgBIg6gDIgWAAIgDgBQAAgBAAgBQAAAAABgBQAAAAABAAQABAAABAAIAmABIDjAWIA7AGQAAABABAAQAAAAABgBQAAAAABAAQAAAAABgBIABABIAAAEIgDABIgKgDg");
	this.shape_14.setTransform(26.7,17.6,0.999,0.999,-120);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#D7D1C2").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_15.setTransform(65,91.5,0.999,0.999,-120);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#E3DED2").s().p("AAAAAIABAAIgBABIAAgBg");
	this.shape_16.setTransform(64.8,92.2,0.999,0.999,-120);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#E3DED2").s().p("AAAAAIAAAAIABABIAAABQgCgCABAAg");
	this.shape_17.setTransform(65.1,91.2,0.999,0.999,-120);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D7D1C2").s().p("AALArIgHgNIgIgbIgGgQIAAgBIgDgLIgCgLQAAgGADgEIABgCIACgBIAAACIABAIQgCACAAAEIACAQIADANQACAGADANIAIATQACAGAEAFIACADIAAACQgCgCgDgFg");
	this.shape_18.setTransform(61.1,96.4,0.999,0.999,-120);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#C9C1B3").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_19.setTransform(45.8,104.3,0.999,0.999,-120);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#E3DED2").s().p("AhZAAIAKgBICMABIAcACg");
	this.shape_20.setTransform(47.2,60.3,0.999,0.999,-120);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#E3DED2").s().p("AjkACIgEgBQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIABAAQAHACALAAIASgBIAQAAIAKgBIAvAAIASgBIARgBIAtgBIA2ABIgJAAIgQABIgIAAIgDAAIgkABQgEgBgDABIgLAAIgUAAIgRABIgDAAQgGgBgHABIgKAAIgTABIgLABIgPABIgXAAIgDAAQgIAAgJgCgADZAAIgLAAIgHAAIAiAAIgCACIgOgCgAAngCIAwAAIAGgBIBgADIAKAAg");
	this.shape_21.setTransform(53.4,70.1,0.999,0.999,-120);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#C9C1B3").s().p("Aj7A/IgCAAQgBAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAHgFIAJgKIAAgBIACgCQAHgKAHgOIAKgYIAIgdIACgLIAAgCIAAgBIABgGQADACAEgCQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABABAAQAAABABAAQABAAABAAQADgBADABIAGgBQADAAABgFIABgGQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIgDAMQgCAKADABIAEAAIAMgEQABAAAAgBQAAAAABgBQAAgBAAAAQAAgBAAAAQACAFAJACQAKABAUAAIAdAEIAMACIAGgBQAEAAACABIAGAFQACAAAIAAIAJAAIAVAEIDSAQQAIABAGgCIAGgBIAQAAQAKgCAKgEIgEAGIgGAGQgLAGgUAHIggAMQgTAIgMALIgMAMQgGAGgJABIhOABIgDAAIgEAAIgCABIgDgBIjjABIgDgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQgEADgGAAIgIAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBIABgBQgGAGgHAAIgYACg");
	this.shape_22.setTransform(43.9,71.6,0.999,0.999,-120);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#D42939").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_23.setTransform(21.6,55,0.999,0.999,-120);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#E9E6DA").s().p("AAAAAIAAAAIAAAAIAAAAg");
	this.shape_24.setTransform(37.1,73.8,0.999,0.999,-120);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#BDAEA1").s().p("AgBAOQABgNABgPIAAgCQACACgBAEIgCAbIgBgDg");
	this.shape_25.setTransform(47.5,92.5,0.999,0.999,-120);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#C9C1B3").s().p("AAAAVIAAglIAAgEIAAgEIAAADIABAgIgBAOIAAgEg");
	this.shape_26.setTransform(43.7,94.5,0.999,0.999,-120);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#E9E6DA").s().p("AAHAoIgCgBQgCABgDgBIAAgBQgCgFAAgDIAAgLIgCgWIgGgfQgCgFACgDQABAAAAAAQABAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAQACAEABAFIAAABIAGASIABADIABAHIABACIAAAGQgBACABADIABAZIgCAGQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBg");
	this.shape_27.setTransform(40.5,92.3,0.999,0.999,-120);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#E9E6DA").s().p("AAQAqIgDgBIgBABQAAABAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgCAAQgCgDgEABIgCABIgDAAIgCgEQAAgDgDgCIgBgCQAAgXgBgKIAAgEIgBgBIAAgCIgBgCIgCgPIgDgMIAAgBIACgCIADABQAGgBACACIAHgBIAGAGIAGAZIADASIAAAWIAAAMIgCABIAAgBg");
	this.shape_28.setTransform(41.3,94.6,0.999,0.999,-120);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#BDAEA1").s().p("AAABHIh1gEIgCAAQAAgBAAAAQABAAAAAAQABAAAAgBQABAAAAAAIARAAQA0AAAKgBQALgCAGgGIAGgKIAGgEIAGgEQACgCADgCQACgDADAAQADAAADgDIASgIQAEgCACAAIAAAAQACgDAEgBIAGgBIALgEIANgGIAFgDQAEgBAGgHIABgBIAFgFQAFgHADgGIADgHIAGgNIADgJIAEgOIABABIAAABIgIAZIgJAVIAAAAIgJASIgEAEIgNAPQgBACgEACIgCACIgFAHIgBAAIgKAIIgDADQgFAGgDABIgBABIgJAMIAAAAIgBAEQgFAFgGABQgHABgEAAIgBAAQgCABgEAAIgDAAg");
	this.shape_29.setTransform(35.2,57.7,0.999,0.999,-120);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#E3DED2").s().p("AClAoQgCgCgEABIgIgBIgCACIgDgBQgEADgDgDIgCgBIgKABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAIgEACIgCgEIgEABQgHACgHgEQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAgBAAIgEACQgDgEgDADQgHgEgGABIgBAAIgJAAQgGAAgDgCIgDABIgDgBQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgDgBIgEgBIgDgCIgCAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQgDAEgFgDIgDAAQgEACgDgDQgCACgDgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBABgEgCIAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAgBAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgCgCgHADIgCgBQgGgCgDABQgDABgDgDIgBAEQAAABgBAAQgBAAAAAAQgBAAAAAAQgBgBAAgBQgDgEgGAAQgJAAgCgCIgCAAIgFAAIgFgBIgEABQgDADgDgEQgFgHgHAEQgDABgEgCQgIgDgGACQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAAAgBIgEgDQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAQgEACgDgCQgEgCgDADQgCACgDgDQgCgDgFABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQgEgDgEAAIgDgBQgEgCgDACQgDgBAAgEIgBACQAAAFgGAAQgDgBgEACQgBABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBIACgKQgDAGgIgBIgEAAQgDABgDgDQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgFABgBgDIAAAAIAEgdIADAEIADAAIAEgBQADgBAFAEQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAIADgDQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAAAAAQABgIABgEIAAAXQACADAEgCIAGABIACgDIAAAAQABAAAAgBQABAAAAgBQAAAAABgBQAAAAAAgBIAAgFIABgFQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBABIAAAEQAAACACADIAIABIACACQADABAGgDQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAIgBIABACIADAAIAEABIAIABIACABIACABIAHACIADgDIAFgBIADACQABABAAAAQABABAAAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABIACABQABABABAAQAAAAABAAQAAAAABgBQAAAAAAgBQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAIADAAIABgDIAAADIADACQAAAAABAAQAAAAAAAAQABAAAAgBQABAAAAgBIADABIADAAQADAAADADQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIACgBIAJADQABAAABAAQAAAAABABQAAAAAAAAQABAAAAAAQACAAACgBQADgBAEACIACgCIAEACIAEgBIAEABIABABIACABQADgCAGAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAIAEACIAEAAQACAAACABIACgDQAEABABACQAAAAABABQAAAAAAABQABAAABAAQAAAAABAAQABABAAAAQABAAAAAAQABAAAAgBQABAAAAAAQACgCADACIABABIADAAIACAAIACgCIABACQABAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAAAQACADAEAAIADABIAFgCQADgBABgCIABADIABACQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAgBQAGAAADAEQACAAADgBQADgCADADIACAAIACACQAGABABgCIADACIACgCIAFAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAgBQABABAAAAQAAAAAAAAQAAABAAAAQAAAAAAABQAFACAEgCIAFAAQABABAAAAQABAAAAgBQABAAAAAAQABgBAAAAIAJACQACgCAFABIACADQAEgCALACIABAAQAAABABAAQAAABABAAQAAAAAAgBQABAAAAAAQAEgCAEACQAEACADgCIAFgBIAFADQABAAAEgCQADACALAAIABACQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAIADABIAFgEIAGABQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIACgCQACgCAEAAQAAACgCAEIgKAMIgRAGQgGACgDgCIgDABQgBABAAAAQgBAAAAAAQgBAAgBAAQAAgBgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBABgBAAQgCADgIAAIgFAAIAAABIgEgCg");
	this.shape_30.setTransform(38,71.1,0.999,0.999,-120);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#998877").s().p("AgHB5IgBgIIAAgCQgDgGAAgHIgBgBIgCgBIAAgBQABAAAAAAQABgBAAAAQAAgBAAAAQAAgBgBAAIgJghIgBgKIgCgDQAAgCgBgDIgBgGQABgBAAAAQAAAAAAAAQAAgBAAAAQAAAAgBgBIgCgHIAAAAIgCgIIgBgHIAAgHQABAAAAgBQAAAAAAAAQAAAAgBgBQAAAAgBAAIgBgCIAAgFIgBgBQgBgHABgEIABgKIgBgGIgBgEIABgJIAAgIIABgFQABgEgBgDIAAgCQAAgEAEgBIgBgCIACgCQADgDABgFIAAgBQACgCABgFQAAgDAEgDIACgEQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBAAAAQAEAAACgEIAEACIAEgDIAHgEIAEgBIAIgEIABAAIABABIAAABIADAFIAAABIABACQAAACACADIAEAMIADASIABACIAAAFIAAACIABAZIAAAVIAAAFIgBABQAAALgDASIAAAEIgBAFIAAACQgDAagKAZQgIAWgKAQIgBADIgCACIgBABIgBAAIgCAAg");
	this.shape_31.setTransform(49.1,95.6,0.999,0.999,-120);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#E9E6DA").s().p("ADGA+IgFAAIgBAAQgBgBgEACIgBAAQgCgDgDACIgCgCIgNACIgFgFIgCABIgDgCQAAAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAIgCADIgCgDQgDAAgEADIgCgEQgEACgCAAIgCgCIgEgBIgDADIgGgCIgFABIgFgDIgFACQgEgBAAgCQgGADgFAAIgCgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIgJADIgIgDIgDACIgCgBIgGAAIgJgDIgDAAIgHgBIgIAAQgCgCgEABIgFADQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBAAgBgBQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgDABQgDACgDgDQgBgBgEAAIgBABIgEgBQgEAAgCgBIgEABQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAQgDADgDgDIgCAAQgDAAgDgDIgDABIgEgBIgDgBIgHgDQAAAAgBABQAAAAAAABQABAAAAAAQAAABAAAAIgBABIgEgDIAAABQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAgBIgHgCIgDAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAgBIgBgDIgEgCIgEACQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgDACIgDgCIgDABQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgEABIgEgBIgBAAIgFgBIgFABQgDgCgCgFIgBADIgEACIgCgDQgDgBgCABIgDgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIgEADIgDAAIgEABIgCgBIgBgBQgDABgCgDIgCgCIgDACQgDgBgCABQgGgCgGAAIgKgCIgEABQAAAAAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgCAAQgCABgDgBIgFgDIgFgBQgCgCgBgHIgCgSIAAgCIgBgFIAAgBIgBgDIAAgBIgBgGIAAgBIgCgKIgEgQQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAIALAAQAEADACAAIAEACIACgBQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIgBACIABAAIAFgCIABAAIAIACIAGACIADgBQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIACADIABgDQABAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIACADIACgDIACABIABACQAFAAACACQABAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQAEgBADACQADADADgBIAFAEIADgCQAEABACgBQADABAAADIAIgBIADACIADgBQAAAAABABQAAAAAAAAQABAAAAABQAAAAABAAIACgBQAAAAABAAQAAAAAAAAQABgBAAABQABAAAAAAIADAAIADACIAHAAQABAAAAABQABAAAAAAQAAAAABAAQAAABAAgBIADADIAEgCIACAAIAKACIAFAAQAEAAABADIABABIANABIAIABIACAAQACgBADACIABACQABABAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAIADAAIACACIABgBQAEACAJAAQAFgCAEAEQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAABgBQADgBACABIALAEIADABIAEgBIACACQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQADgBAFAEIAGgBQADgBADACQAEABADgBIACAAQAFAHAHgDIACABIAFgBIAFADIADgBIAEABIAEABQACAAADAAQADAAACAAQAHAEAIgDIABAAQABACAHABIACAAQAFgCADAEQADACAEgCIADADIAFACQABAAAAAAQAAAAAAABQABAAAAAAQAAAAABgBIACAAQACABAFgBIACACIADgBIACACIAFAAIADAAQAFAHAFAAIAFAJIABADIgCAKIgCAEQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABIAAADQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgBADIgCABIgDABIgBACIgCACIgEgBg");
	this.shape_32.setTransform(31.3,71.8,0.999,0.999,-120);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#C9C1B3").s().p("AAAAAIAAAAIAAAAIAAAAg");
	this.shape_33.setTransform(37.6,39,0.999,0.999,-120);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#D42939").s().p("AAAAAIAAAAIAAAAg");
	this.shape_34.setTransform(45.2,41.7,0.999,0.999,-120);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#D42939").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAABg");
	this.shape_35.setTransform(39.3,26.3,0.999,0.999,-120);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#D42939").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAAgBg");
	this.shape_36.setTransform(47,42.8,0.999,0.999,-120);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#D42939").s().p("AAAAAIABAAIgBABIAAgBg");
	this.shape_37.setTransform(43.7,41.4,0.999,0.999,-120);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#D42939").s().p("AAAAAIAAAAIABAAIgBABQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_38.setTransform(41.8,41.4,0.999,0.999,-120);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#D42939").s().p("AgBAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIACAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgCgBg");
	this.shape_39.setTransform(44,41.4,0.999,0.999,-120);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#D42939").s().p("AgBAAIABAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABABIgBAAIgCgBg");
	this.shape_40.setTransform(32.5,49.4,0.999,0.999,-120);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#D42939").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAgBAAQAAAAAAAAIAAgBIABABIgBACg");
	this.shape_41.setTransform(42.3,41.4,0.999,0.999,-120);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#D42939").s().p("AgBAAIABgBIAAABIABAAIABAAIgBABg");
	this.shape_42.setTransform(39.4,25.9,0.999,0.999,-120);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#D42939").s().p("AgEgBIADgCQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAAIABABIAAAAIABAAIABABIAAAAIADABIgCACg");
	this.shape_43.setTransform(39.2,27.1,0.999,0.999,-120);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#D42939").s().p("AgDACIAAAAQABgBABAAQAAgBABAAQAAAAAAAAQAAAAAAAAIABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABABQAAAAABAAQAAAAAAABIgCACIgBAAIABABIgBACIgDgCg");
	this.shape_44.setTransform(44.7,41.4,0.999,0.999,-120);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#D42939").s().p("AgDAEQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAABIABgBQAAgBgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAABABIABgCQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABAAIgFAKIgCgCg");
	this.shape_45.setTransform(40.5,41.5,0.999,0.999,-120);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#998877").s().p("AAJAGQgBgCgEgBIgEgBIgJgBIAEgGIAKAGIAFAFg");
	this.shape_46.setTransform(37.5,40.5,0.999,0.999,-120);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#D7D1C2").s().p("AgQAEIABgDIADgDIAGgBIAQAAIABAAIABABIABABIADABIABAAIgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgFgBgFABIgEAAIgEABIgHACIgCAAIgCAAg");
	this.shape_47.setTransform(38.5,40,0.999,0.999,-120);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#BDAEA1").s().p("AAGAEIgJgDIgKgBIgBAAQADgBADAAQAEAAADgBIABgCQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIAJgBIABAAIADABIgBAEQgBACgEAAIgGAAIAGAEIAEADIABABIgIgEg");
	this.shape_48.setTransform(46.8,46.8,0.999,0.999,-120);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#998877").s().p("ACQAfIgsgFIgFgCIgEAAIgagDIgPgBIg7gHIgJAAIgtgFIgJAAIgJgBIgSgBIgHgBIgBAAIgOAAIgOAAIgMAAIgBABIAFAFIACABIgBABIgegWIgBgCQAIgFAEgMIACgBQAAAAAAAAQAAABABAAQAAABAAAAQABABABAAQAFABAMADQAFABAIAEIABABQABABAAAAQAAABABAAQAAAAABAAQAAABABAAIAAAAIADAEIAEACIATADIBrAJIBeAKIA1AGIAEAAIALACIAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBAAQgEAEgHAAg");
	this.shape_49.setTransform(25.5,21.3,0.999,0.999,-120);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#998877").s().p("ADSAsIgsgDIgMAAIgigCIgWgBQgGABgHgBQgLABgFgBIgCAAQgEABgEgBIh0ABIgLAAIgDAAIgJAAIgFAAIgJABIgMAAIgSAAIhYADIgKABIgKAAIgKAAQgNgBgFgIIgEgEIgCgDIABgBQAIABAIgBIADAAIADAAIABgBIAfAAIADAAQAGACAJgBIAPgBIDVgBIADAAIAEgBIAEABIABgBIAzACIBMACQAKAAANgDQAGgBACgGIAFgJQADgEAFgDQAFgCAHgHIARgRIALgMIAGgJQAAgBABAAQAAAAAAAAQAAgBABABQAAAAAAAAIgJAVIgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIgpBBIgEAGQAAgBAAgBQAAAAAAgBQABAAAAAAQAAgBgBAAg");
	this.shape_50.setTransform(47.5,70.5,0.999,0.999,-120);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#E3DED2").s().p("AAzAMIgGgBIgHgCIgIAAIgzgHIgUgCIgSgCQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIBpAMIADgBQABAAAAAAQAAgBAAAAQAAAAAAgBQAAAAgBgBIAAAAQAAgGgEgEIgCgFIACgBIACAAIAEABQAAABgBAAQAAAAAAABQAAAAAAAAQABAAAAABQACACACAFQABAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgCACAAAFIgBABIgDABIgCAAg");
	this.shape_51.setTransform(21.7,7.5,0.999,0.999,-120);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#BDAEA1").s().p("ACrA0IhbgKIgXgDIiKgOIgWgBIgJAAQgQgCgSAAQgJAAgCABQgDAAgDgEQAAgBAAAAQAAAAAAAAQABAAAAgBQAAAAABAAIATAAIBwAHIAUACIASACIAnAEIAZADIBHAHQAIAAAFgDQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQgFgCgDAAIgMgBIhggLIhHgIIhegJIgJgCIgDgCQgFgGgPgEIgQgEQgEAAABgEIACgGIABgBIABgDIAAgBIAFgXQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAAAQgBAJAHABIAJADIAIAAQAGgBADAFIAEAAIACACIADgCIACABIADgDIACAEQAAAAABABQAAAAABABQAAAAABAAQAAAAABAAIACgBQAAAAABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABgBIACADIACADIAEAAQABAAAAABQABAAABAAQAAAAAAAAQABABAAAAIgCADQgBABAAAAQAAABgBAAQAAAAAAABQAAAAAAABIACADQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBAAQAAADgCAEQABACAEABQAEABAEgBQACACAIABIAWADIAFABIASACIASACQAGgBAKACIBCAHIAaADIAJABIAGABIALACIAGAAIAhAEIAOACIAAABIgCABIgGgBIAAABIAFAIIABAAIABADIAAAEIgCAAIgBAAg");
	this.shape_52.setTransform(23.7,20.7,0.999,0.999,-120);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#D42939").s().p("AAAAAIAAAAIABABg");
	this.shape_53.setTransform(23,40.7,0.999,0.999,-120);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#D42939").s().p("AAEA9IgDAAQgBAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIABgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBABAAAAIACgDIgPgDQgKgDgHgFIgBgBIgCgDIgCgBQgGABgDgDIgBgDQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgBgBIgEgBIABgEIAQggIAAgCIAIgRIAKgcIAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIgCgBIACgBIABACQAGADAOAEIARAHQAOAFAIAAQAJAAACABIACgGIAJAiQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBQgBgCgEgDQgDgDgBgDIABgFIAAgEQgCgFAAAHIgBACQgBABAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIgCAFQAAABAAAAQAAABAAABQgBAAAAAAQAAABgBAAIABACIgCAAQABAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQgJAXgRAmQgBABAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAIAAACIgCABQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAACgBADQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQACACgCAEg");
	this.shape_54.setTransform(27,45.5,0.999,0.999,-120);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#D42939").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_55.setTransform(37.8,37,0.999,0.999,-120);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#E9E6DA").s().p("AAAAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_56.setTransform(37.8,37.2,0.999,0.999,-120);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#BDAEA1").s().p("AgBAAIABgBIACACIAAAAIgBABQgBgCgBAAg");
	this.shape_57.setTransform(47.5,42.1,0.999,0.999,-120);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#998877").s().p("AAAAAIgCgBIAAgBIAAAAIACACQAAAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAAACQgDgBAAgCg");
	this.shape_58.setTransform(47.7,41.4,0.999,0.999,-120);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#C9C1B3").s().p("AAHAHIgGgHIgBgBIAAgBIgIgEIAAgCIAGADIACABQAFAEAEAHIAAABIgCgBg");
	this.shape_59.setTransform(36.6,97.9,0.999,0.999,-120);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#C9C1B3").s().p("AAJAHQgHgKgLgEQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQADgBAGADIABACQAFAEAFAGIABADQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAg");
	this.shape_60.setTransform(36.2,96.6,0.999,0.999,-120);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#D42939").s().p("AgJABIgBgBIgBAAIgDAAIgBAAIgBAAIgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAMAAIAQAAIABAAIAEAAIAEAAQgHACgWgCIABAAIAAABg");
	this.shape_61.setTransform(21,55.1,0.999,0.999,-120);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#C9C1B3").s().p("AgJAPIAKgPIACgDQgDgDAEgEQACgDAGgDIgGAKIgPAWIgBABIABgCg");
	this.shape_62.setTransform(45.8,50.1,0.999,0.999,-120);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#D7D1C2").s().p("AgDAGQgDgGgHgDQgBAAAAgBQAAAAgBAAQAAAAAAAAQgBgBAAAAIASAFIAGAAIAIACIABADIgCABIgJgEIgEgBIgFgBIABAEIAAACg");
	this.shape_63.setTransform(36.8,99.8,0.999,0.999,-120);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#998877").s().p("AAUATIgQgOIgagWIgBgDIAGAFIACACIABABIAJAGIABACIACABQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAVAOIADADIAAAAIAAAAIgBAEQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBg");
	this.shape_64.setTransform(39.7,25.7,0.999,0.999,-120);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#D42939").s().p("AAeAaIgDgDIgDgDIgCgBIg2gsIgBgBIADACIAJAHQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAAACIACAAQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAIACAAIAAACQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBABQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIACAAQAAABABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIACAAIAAACIACAAQAAABAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIACAAQAAABAAAAQABAAAAABQAAAAAAAAQAAABAAAAIACAAIAAABIACACIABABIACAAIABACIACABIABABIABACIACAAIAAACQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIABACQAAAAABAAQABgBAAABQABAAAAABQABAAAAABIAAABQAAABABAAQAAAAAAAAQAAAAABAAQAAAAAAAAIABABIACABQABAAAAAAQAAAAAAABQAAAAAAAAQAAABgBAAIACAAIABAAIgBACIgDgBg");
	this.shape_65.setTransform(38.5,32.1,0.999,0.999,-120);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#D42939").s().p("AgBAMIgEgEIgBgCIgCgEIgBgCIACAAQAAAAAAAAQABAAAAAAQAAAAAAAAQgBgBAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIABgBIABABIADgBQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBABAAIgBgDIAEgDIABgCIAAAAQABAAAAAAQABAAABABQAAAAAAAAQABABAAAAIgHALIgCAFIgBAEIAAABIgBAAg");
	this.shape_66.setTransform(46.6,41.6,0.999,0.999,-120);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#998877").s().p("AAQAHIgogLQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABIAAgCIAAgCIADAAIAyAJIgBgBQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIgPgCQABADAFADIgCABIgBgBg");
	this.shape_67.setTransform(36.8,21,0.999,0.999,-120);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#998877").s().p("AAMAPIgCgDQgJgKgDgCIgBAAIgBAAIgIgFQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQAIgCACgFQADAHACAEIAKAPIACADIACAEIgCAAg");
	this.shape_68.setTransform(46.6,44.5,0.999,0.999,-120);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#C9C1B3").s().p("AAhANIgMgJIgLgEIgRgEIgTgCIgJgBIgBgBQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIgBACQABAAAAAAQABAAAAAAQABAAABAAQAAAAABAAIAOgEIATgCIAEgBQAAABABAAQAAABAAAAQgBAAAAAAQgBABgBAAQgHADgDAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABAAAAQARACAJAGIADAAQAEADAJAJQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQgCAAgCgDg");
	this.shape_69.setTransform(47.8,46.7,0.999,0.999,-120);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#D42939").s().p("AAmARQABgDgDgCQgEgBgCgCIgCAAIgBgBIgHgDIgEgBIgGgDIAAAAQgHgBgDAAIAAAAIgBgCIgDAAIgJgCIgBgCIgBABQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgCAAIgCgCIgDABQgFgDgCgCIgCAEIgBAAIAAgBIABgCQAAgGgDgDIgBgCIAEABIACABIAMAEIAAAAIAEABIACABIAMAEIADADIABAAIADABIABABIACAAIAFACIABAAIAJAEIABAAIABAAIACAAIAEABIADABIAAAAIACACIACAGQACAGgBAIIgBgHg");
	this.shape_70.setTransform(18.5,48.3,0.999,0.999,-120);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#91091E").s().p("AA0AjIgRgBIgGgCIgKgDIgEgCIgIgDIgGgCIgDgCIgMgEIgCgCQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIgCgBIgFgJIgBgDIgDgDIgBgBIAAAAIgBgCIgCgCIAAAAIgBAAIgDgEIgBgBIgBgBIgEgDIgBgBIgBgBIgLgFIgCgBQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIALABQAJABAIgBQgFAAAAgCIABgCIAFgFIAEgDQAFgCADABIACAAQAEADgBAIIALADIA7AVQADABAAADIAAAJIgBAAIAAACIAAABIgBAKIAAAAIgBADIgCAHIgEgBg");
	this.shape_71.setTransform(20.6,49.7,0.999,0.999,-120);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#C9C1B3").s().p("AjPB5IgJgDQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgCgCIgBAAIgBgCIgEgEIAAgBIgBgCQgEgFgIgTQgDgHgGgSQgGgVAAgMIABgGQABgEgBgHIgBgPQABgCAAgIIABgmIABgcIABgCIAAgBIAAgBIAAgBIAAAAIAAgBIAAgBIAAgDIABgDIAAgBIABgEIgBgBIABgCIAAAAIAAgCIAAgCIABgCIAAAAIAAgDIABAAIAAgDIABgCQAEgBAGACIgCACIgBAEQAAABAAABQAAAAABABQAAABAAAAQAAABABAAIABAGQgDAEAAACIAAADQABAAAAABQAAAAAAAAQAAABAAABQAAAAgBABIADAEIgBAGQADAFgDADIACAHQADAGgDAEIgBACIACAGQABAGgDACIABAEQgCADADAEIABAAIABAFIABAFIABAGIgBAJIABADQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAIAAAEQACACAAAFQgBADACAEIACAKIgBACQABABAAAAQAAABAAABQAAAAAAABQAAAAAAABQACAHgBAHIABAFIACAEIgBAGIAAAFIAAADQADAGgDAHIAAADIAAACQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQgHgFgDgIIgCgEIgBgBQAAAEAEAHIgCAAIABADIAFALIAGAHIACABQACAFAIAFIAGACQAOABAMgBIAlgCIAVgBIAjgBIAigBIAJAAIARgBIBCgBQAHABAOgCIBLABIAEABIAkABIAZAAIAyADIAGABIgBADQgKAAgFgCIgMAAIh9gEQgYgBgMABIhDABQgLABgGgBIgLABIhXAEIhGADIgIAAIgOgBg");
	this.shape_72.setTransform(44.1,78,0.999,0.999,-120);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#BDAEA1").s().p("ADwCYIACgDIABgDIACgEQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIgRgBIgTgBIj7gCIgyABIhbAEIgXABQgNgBgDgDIgFgEIgLgOIgFgKQgBgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQgEgHAAgEQABAAAAAAQAAAAABABQAAAAABAAQAAABAAABQAEAIAEAEIAFAEIABgPQgBgJAAgGQAAgBAAAAQABgBgBAAQAAAAAAgBQAAAAAAAAQgCgDABgGIgCgKIAAgJQABgFgDgEIgBgJIgBgEIAAgGIgBgEIAAgGIAAgGIgBgDQAAgGgEgGIAAgCIAAgEQAAgDABgCQABgCgBgFQgCgFACgEQACgEgDgEQgCgGACgDIgBgEQgCgDACgDQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBIgBgFIABgDQACgEgCgGQgDgIAGgCIAGAAIAMABIAFAAIACgFQAFgQAFgLQAEgJAIgJQAFgFAFgCQAFgCAFABQAHACAEAGIADAFIgDACIgEABIgNAHQgFADgEgCQgEAEgDAAIgBABIgDAFQgDADgBADIgDAJQgBAFgEACIAAADIAAABQgDACAAAEIAAAHIgBASIAAAOIAAAGQgBAHABAHIACALIABAHIACAKIACAIQACAGgBAEQAAAEADAGQABADABAHIADANIAEANIACALIADANIACALIADACQAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBABQgIAIgEADIABACQgBAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAQgJABgJgBQAAAAAAABQAAAAABABQAAAAAAABQABAAAAABQAIAMASgBIBFgDIATAAIASgBIASgBIAKABIAlgCIAzAAIAqgBIBBABIAuACIAmACIAcACIAGABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAIgJAPIgBABg");
	this.shape_73.setTransform(41.5,78.4,0.999,0.999,-120);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#E3DED2").s().p("ADNAaQgBgFgUgCIgagBQgdgCgcACIgDAAIgKgDIgKADIgQAAIgRAAIgKgEQgDgBgRAAIgWAAIgYgCQhpgGgzgGIgLAAQgFgCgBgDIgBgCIgBgCIAAgDIAAgCIgBgHIAAgCIAAgCQAFgBACADQAAABAfgCQAQABAMgBIAQgBIAlAFQAVADAPAAIA0ACIAkABQAVABAOACIAKADQAGABADAAIAHgDQACAAAFACQAMACAogDQASgBAJABQAHAAAGACIAHACQABAAAAAAQAAAAABAAQAAgBABAAQAAgBAAAAIABAIIABAKQABAKgDAHIgBgBg");
	this.shape_74.setTransform(15.6,20.6,0.999,0.999,-120);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#E3DED2").s().p("ADMBXIgEAAQgDAAgEgBIgEAAQgCACgFgCQgDgCgCABQgEABgEgBQgEgCgDACQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAQgJgEgHADQgCgDgEAAIgbABQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgFgBIgHAAIgGABQgEAAgCgCIgGgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgGgFgFADIgCgDQgHADgCAAQgGAAgDgDIgCACIgDgCQgFADgEgDQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgFACgEgEQgDgDgCACIgBABIgGgBQgFAAgDgDQgCgCgGADQgDABgCgCQgCgDgDABQgEACgDgDQgDACgDgCQgBAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBABQgDACgCgDIgCgBQgKgCgGAAIgCgBQgEgDgKACQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQgBADgEgDQgEACgEgDQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAQgDACgDgDQgEgEgEAEQgBABAAAAQgBAAAAAAQAAABgBAAQAAAAgBgBIgOgDQgFAAgHgDQAAAAgBAAQAAAAgBAAQAAgBgBABQAAAAgBAAQgEABgCgDIgDABQgEACgDgDQgCgBgFAAQgEgBgBgDIgDAGQgBACgFgBIgFAAQgEABAAgFIABgTIgBAJQgBABAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgBgCIgDABQgEADgEgDQgCgCgEACQgFABgDgFIgBgGIAAgCIABgKQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAAAABgBQACAAACAEIACAEIAHgBQACgBADACIADABIACgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAIABgDQABghgHgZIgEgNQgCgIgIABIgFAAQgGgBgFABIgCgBQgCgDAAgDIgBgCIAAgBIgBgBIgCgEIgBgCIAAAAIgBgHQACgBAFACIAOAFQACAAADACIAEAGIABABIAAAAQgFgHgFgFIgCgCIAGABIAEABIAFADIgBgCIAFABICpAnIDsAqIABAAIAIAAIABABIABAAIADABIAAAAIABAAIABAAIAFAAIABABIACABIACABIABAAIABABIABABIABABIADACIAFAFIABAAIAAABIABACIACACIABABIAAAAIABABIABACQAAABAAAAQABAAAAABQAAAAgBAAQAAABAAAAQgDAAgCgCIgEgEIgOgDIgBAAQgIAAgIgDIgCgBQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgEABgCgDQgCgBgEAAQgFABgFgCQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQgFABgGgCQgDgDgEABQgDABgCgBQgEgCgGAAIgBAAQgEgBgLAAQgEAAgDgCQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgCAAQgEgBgKAAQgJgDgFAAIgDgCQgCACgFgCIgKgEIgEABQgDABgCgCQgCgBgEAAIgMgBIgKgCIgIgBQAAABAAgBQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAQgDABgHgCIgKgBQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgJAAIgDgBQgEgCgEACQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAgBQgCgCgGgBIgIgCQgDgBgCACIgCAAIgDgBIgEgBIgGAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQgBAAAAAAQgFgBgCABQgBABAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIgGgDIgGgCQgDgDgDADQgCADgDgDIgDgBQgCAAgDgCIgDACIgBgBIgCgCIgCACQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgCgCQgDACgHgDQgGgDgEACIgEABIgBgDIgNgEIgFgBQgHAAgCgBQAAABgBAAQAAAAAAABQAAABAAAAQAAABABABIAFAVIAAAEQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIgGgUIgDgHQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAAAAAIgEgCIgDgBQgCACABAEQAGASACAZQABAMAAAKIACAIQAAABAAAAQABAAAAABQABAAAAAAQABAAABgBQAEgBACAEQACgDAAgEIgBgVQAAgEABgBQAAAAABABQAAAAAAABQAAAAAAABQABABAAAAIABATQABAEAFABQACABADACQADACADgBQADgBAGABIAHACIANABQAFABADgCQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQACAEAGAAQAGABAEgDIACABQAAABAAAAQABABAAAAQABABAAAAQABAAABAAQADgBADADQADAAABgDIACACQADAEADgBQAEgBAHACIAIABIAFABIADgBIADABQAGgBAEAFQADgCAKADQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAIABgDQABAAAGACIAMAEQAHADADgCQAAAAABAAQAAAAABAAQAAAAABABQAAAAABABQADgBADAAIALABQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQADACADgBQADgCACADIAEADIADgCQAEgCAEABIACABQAFgBAJACIAQADIADAAQADgCADACQAEACAIgCIADAAIABADQAEABADgCQAEgCACADQABAAAAABQABAAAAAAQABAAAAAAQABgBABAAQACgCADACQAAABAAAAQABAAAAAAQAAABABAAQAAAAABgBQAEAAAFABQAGgEAFAEQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAEgDACAFIAEgCQABAAAAAAQABAAAAAAQABAAABABQAAAAABAAIADgDIAEABQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQADADAFgBQAHgDADADIADAAIADACIAHgBIAGAAQABABABAAQAAAAABgBQAAAAABAAQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBABAAIADgBIADgEQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAgBIACgCQAAAAABAAQAAABAAAAQAAAAAAAAQABABAAAAIgGAPIgGAMIgLAGIgBABIgKACIgFABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBg");
	this.shape_75.setTransform(32.4,74.5,0.999,0.999,-120);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#91091E").s().p("ABxCEQgIgEgPgMIgBgCQgBgDgDAAIgBgBIAAgBIgBAAIgCgBQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIAAgBQgEgBgCgDIgBAAIgBAAIAAgCQgEgEgDgBQAAgCgEgCQgFgBgDgFIgIgHIgCgCIgCgCQgEAAgEgFIgEgDIgJgHIgQgNIgBAAIgBgBIgBgBIgBAAIAAgBIAAgBIAAAAIgCgBIAAgBIgCAAIAAgBIgBAAIgBgBIgBgBIgBgBIgDgCIAAgBIgBAAIAAAAIgDgBIgBgBIgBgBIgQgNIgIAOIgCAFIgCACIgBABIgCAAQAAABAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAABQABAAgBABQAAAAAAAAQgBABgBAAQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIABABIgBACIgBABIABAAIgBABQAAABAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIABABQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgBAAQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIABACIgBABIgCAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABgBAAIAAAAIgBAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIABABIAAABIgCAAIAAACIAAABIgDAAIACACIAAABIgCAAIgBACIgCAAIgDADIgBABIgBACIAAAAIgDADIAAADIgEACIAAAAIgDACIgCgBIgDABIgBAAIgBgBQABAAAAgBQAAAAgBAAQAAAAAAAAQAAAAgBAAIgBgBIgJgRIgIgLIgCgBIgBAAIgKABQgRACgIACIgNACQgDACgCgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBIACgBIACgDIABgBIAOgTIAGgLIAEgFIAAgBIADgEIAAgBIAJgPIAJgMIAQgZIASgeQADgEACAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIADACIAHAIQAEADAFAAQADgBAHAIQAJAGAMABQAEAAABACIACACIACAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAIgBADIADAAQABAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQADgCADgIIADgFQADgDABgGIAEgKIAIgSQAGgNACgIQABgFACgGIADgKIACgCIgBgCQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAQgCAFAAAEQAAAAABABQAAABAAAAQAAABABAAQAAABAAAAIAFAFQADAEgBACIABABIABABIAAACIABAAIAAABIAAAEIABABIAAAAIAAACIAAAAIABACIAAABIAAACIABAHIAAACIAAADIAAACIAAAPIgBACIAAAJQAAAEgCAHIgCAJIAAADIgBABIgBADIAAABIgCAFIgBABIgIANIgFAEIAfAYIAAABIAJAHIACABIABABIACACIAJAHIACACIAHAGIACACIABAAIABABIABABIABABIABABIABABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIACABIABABIABABIABABIABAAIACACIAAAAIAEAEIABAAIABABIABABIACABIABABIADACIABABIAnAcIAAAAIADACQAAABAAgBIAHAFIABAAIACACQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgFgBQgMgBghgIIgEAAQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAABIAAABIAAADIgBABIAAAEIACANIAAABIgBABIgBgBg");
	this.shape_76.setTransform(34.1,39.1,0.999,0.999,-120);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#C9C1B3").s().p("ACKA5IgEgBIgCgBIisgUIgrgEIglgFIgBAAIgGgCIgGgBIgEgBQgCgBACgLQACgKACAAQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgEgBIgCgDQgCgCgHgBQgHAAAAgFQgHAEgIgDIgFgDIgGAAQgVAAgBgNIAAgEIAAgBIAAgHIABgCIAAgGIAAgEIAAgBIgBgBIABgEIABAAQACAAACAEQACABAFABIATACIBxAKQBKAFBKACIBJADIAaAAQATACACAHQABAEgCAHIgDAKIAAAAIgBAEIAAACIgBABIgBAEIgBACQgCAHgEAGIgBADQgEAHgKAKIgMAJIgIADIgDABg");
	this.shape_77.setTransform(20,18.1,0.999,0.999,-120);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#E3DED2").s().p("ADKAyQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAIgDgBQAAABgBAAQAAAAgBABQgBAAAAAAQgBAAgBAAIgFgBIgPAAIgDAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAQgHAAgDgBQgCgBgDACIgEAAIgJAAIgHgBIgFABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBQgHgBgDACIgEgEQgCACgMAEIAAgDIgGABQgBAAAAABQgBAAAAAAQAAAAgBgBQAAAAgBAAQgCgDgDACIgCAAIgKgBQgCABgDAAIgGgBIgDABIgGACQgDAAgDgCQgCgCgDACQgFACgEgDIgDABQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgDgDgEACIgCgDIgDACIgDABIgDgCQgDgBgDACIgEgCIgDgBQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCgCQgEgCgGACIgFgBQgDgBgEABQgGACgCgFIgBgBQgGAEgDgBIgBgCIgCAAQgEACgDgDIgBgBQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgEADgFgDQgHABgEgBIgEAAQgBAAgBAAQAAABgBgBQAAAAgBAAQAAgBgBAAQgDgDgDACQgBAAAAABQgBAAAAAAQgBAAgBAAQAAAAgBAAIgEgBIgNgEIgCAAQgEABgEgBQgCACgDgCQgGgDgEAEQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBgBQgDgDgJAAIgBAAQgDgBgFAAIgJgBQgGgCgEABIgBgBIAAAAIgBgDIAAAAIAAgBIgBgDIAAgBIAAgBIgBgBIAAgBIAAgBIAAgBIgCgIIgEgLQgDgEABgIIABgCIAAgCIABgIIABgBIAAgBIAAgCIAAAAQABgNgDgGIAAgBQABgBAAAAQAAAAAAAAQABAAAAAAQABgBAAAAIAbAEIDYASIAnABIBKADIARABQAIABAJAEQAJAGAEAHIAHAKIAFANQAEAJACAPIAAAIQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAQgDgEgEACg");
	this.shape_78.setTransform(10.9,24.1,0.999,0.999,-120);

	this.addChild(this.shape_78,this.shape_77,this.shape_76,this.shape_75,this.shape_74,this.shape_73,this.shape_72,this.shape_71,this.shape_70,this.shape_69,this.shape_68,this.shape_67,this.shape_66,this.shape_65,this.shape_64,this.shape_63,this.shape_62,this.shape_61,this.shape_60,this.shape_59,this.shape_58,this.shape_57,this.shape_56,this.shape_55,this.shape_54,this.shape_53,this.shape_52,this.shape_51,this.shape_50,this.shape_49,this.shape_48,this.shape_47,this.shape_46,this.shape_45,this.shape_44,this.shape_43,this.shape_42,this.shape_41,this.shape_40,this.shape_39,this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,65.3,105.6);


(lib.arm = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,0,0,4).p("ACZE8QgGgEgIgOQgZgvgqiiQhLkmgohzQgKgbgWgOQgVgNgVAFQgWAFgJAUQgKAYANAlQAwCSBHEBQAaBgAWBSQAHAbAHAZIAIAY");
	this.shape.setTransform(15.4,37.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("AAkFdIgOg0IgwizQhHkBgwiSQgNgkAKgYQAJgVAWgFQAVgEAVANQAWANAKAcQAoBzBLEmQAqChAZAwQAIANAGAFIgBAFQAAAJgFAFIgDABQgJAEABAHQgYAAgOAKQgGADgIABIgDAGQgKgDACAIIgdACg");
	this.shape_1.setTransform(15.4,37.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,32.7,76.7);


(lib.Tween8 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.arm("synched",0);
	this.instance.setTransform(9.6,32.6,1,1,0,0,0,24.9,72.7);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,0,0,4).p("AgCgcQACAcADAd");
	this.shape.setTransform(4.6,37.2);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-16.3,-41.1,32.7,82.3);


(lib.guy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Tween8("synched",0);
	this.instance.setTransform(29.4,98.5,1,1,0,0,0,10.6,40.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-5.5},14).to({rotation:0},15).to({rotation:5.2,x:29.3},20).to({rotation:0,x:29.4},17).to({regX:10.5,rotation:-6.4,x:29.3},18).to({regX:10.6,rotation:0,x:29.4},21).wait(1));

	// Layer 3
	this.instance_1 = new lib.diploma("synched",0);
	this.instance_1.setTransform(-2.4,-16.3,0.838,0.838,0,0,0,32.6,52.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-7.2,x:-18.6,y:-8.5},14).to({rotation:0,x:-4.9,y:-14.3},15).to({regX:32.5,rotation:15,x:10.1,y:-16.3},20).to({regX:32.6,rotation:0,x:-5.4,y:-13},17).to({rotation:-9.2,x:-20.6,y:-6.9},18).to({rotation:0,x:-4.9,y:-14.3},21).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3B142").s().p("AAYBZQgWAAgBgEQgBgFACgqQACgpACgDQAEgGAHgRQACgLAAgKQAAgVgKAAIgUgDIgWgEQgIgBAFgEQAFgCAKgCQAPgEASAJQAUAJgCAIQgDAMADAdIAGATQAFANgFApQgFAogGAAIgBAAg");
	this.shape.setTransform(61,50.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,0,0,4).p("AinA3QAPABBWgBQBYAGA5AkQAJgHAAglIAfAGIBnhZImQhDIgvBoIBDAJg");
	this.shape_1.setTransform(51,48.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhAA3QhWABgPgBIAJgmIhDgKIAuhnIGRBCIhnBZIgggFQABAkgKAHQg4gkhYgGg");
	this.shape_2.setTransform(50.8,48.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgVAeQgRgDgLgFQgJgEgHgIIgDgEIgBgCIAFAFQAHAFAKADQAIACATACQAUACAIgCIAGgCIAHgEIAxguQgFAKgJANIgSAUQgGAHgGAEIgHAEIgJAEIgLABIgUgCg");
	this.shape_3.setTransform(47.2,80.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgJAOQgFgFAAgGIAAgGQABgGAEgDQAFgFAEAAQAFgBAFAGQAEAEABAFIAAAGQgBAHgEAEQgEADgGABIAAAAQgFAAgEgEg");
	this.shape_4.setTransform(37.7,61.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgOAGQgBgEAAgDQgBgHAFgEQAFgEAFAAQAFgBAEAFIABACIADACQAFAEgBAFQABAGgFAEQgEAEgFACIgDAAQgJAAgFgLg");
	this.shape_5.setTransform(51,61.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAABWQgKgBgIgDQgLgFgCgNQgDgIABgNQAAgLADgLIAFgVIAehWIgVBYQgDAKgBALIgDAUQgBAOABAFQACAJAHAEQAFAEAJACQANADALAAIAKAAIgKACIgOABIgKgBg");
	this.shape_6.setTransform(44.1,71.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(1,0,0,4).p("AlUntQAVCsAKDHQAJCygHAxQgEAdgxGvQgyGpgIAlQgIAmAPAZQANAXAaAFQAaAFAXgPQAagQAJgiQAUg7APgzQAbhhAaiXQAThuAqivQApirAEgWQABgEAEAAQAEAAAAAEQASBrBFFWQBHFSARA4QAQA3AfAfQAcAcAegDQAdgCAQghQARglgIg8QgXh0gUhxQgljZgxnRQABh8ABiCQAEkJAHgpQAIgoB/kWQCEkcANgfQAMgegEgdQgDgcgQgQQgQgQgVAFQgXAFgWAfQggAtiAEUQh8EMgGAGQgNANgbgNQgdgOAIgQQASgeANgiQAchCABg6QABhGgngvQgogvg7AAQhXAAggAyQgKARgGAZQgGAeAAArQAAA2AGAoQACAOAEANQAFAWASArQALAagIAEQgGACgOgJQgBAAAAAA");
	this.shape_7.setTransform(57.2,142.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FEFEFE").s().p("ACJR/QgfgfgQg3QgRg4hHlSQhFlWgShrQAAgEgEAAQgEAAgBAEQgEAWgpCrQgqCvgTBuQgaCXgbBhQgPAzgUA7QgJAigaAQQgXAPgagFQgagFgNgXQgPgZAIgmQAIglAympIA1nMQAHgxgJiyQgKjHgVisIAcgCQgCgIALADIADgGQAIgBAFgDQAPgKAYAAQgBgHAJgEIADgBQAEgFABgJIAAgFIABAAQAOAJAGgCQAIgEgLgaQgSgrgFgWIgGgbQgGgoAAg2QAAgrAGgeQAGgZAKgRQAggyBXAAQA7AAAoAvQAnAvgBBGQgBA6gcBCQgNAigSAeQgIAQAdAOQAbANANgNQAGgGB8kMQCAkUAggtQAWgfAXgFQAVgFAQAQQAQAQADAcQAEAdgMAeQgNAfiEEcQh/EWgIAoQgHApgEEJIgCD+QAxHRAlDZQAUBxAXB0QAIA8gRAlQgQAhgdACIgFAAQgbAAgagZg");
	this.shape_8.setTransform(57.2,142.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},94).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.7,-60.5,130.2,321.3);


// stage content:



(lib.solution = function() {
	this.initialize();

	// Layer 6
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEFEFE").s().p("AdNdAQhGAAgbglQgcgmAAg7IAAgoQAAg0gbgcQgcgegygBIh0AAIAAC5IBMAPIAABVIkkAAIAAhVIBMgPIAAn4IhMgPIAAhVIE8AAQB4gBBFA4QBEA2AABhQAAA1gcAoQgdAmg3AYQA+ATAcArQAaAqAABAIAAAkQAAAXAKANQAJANAVACIASADIAABVgAXzW2IBiAAQA7AAAegZQAdgZAAgwQAAgvgdgcQgdgdg6ABIhkAAgAKjdAIAAhVIBLgPIAAn4IhLgPIAAhVIIsAAIAADAIhsAAIgHhTIjhAAIAACxIDvAAIAABsIjvAAIAADJIDjAAIAGhUIBsAAIAADBgACpdAIAAhVIBLgPIAAnvIiBAAIgGBOIhrAAIAAi7IJzAAIAAC7IhsAAIgGhOIiCAAIAAHvIBMAPIAABVgAnvdAIAAhVIBMgPIAAnvIiBAAIgGBOIhsAAIAAi7IJ0AAIAAC7IhtAAIgGhOIiBAAIAAHvIBLAPIAABVgA0HdAIAAhVIBLgPIAAn4IhLgPIAAhVIItAAIAADAIhtAAIgGhTIjiAAIAACxIDvAAIAABsIjvAAIAADJIDkAAIAGhUIBsAAIAADBgA+VdAIAAhVIBLgPIAAn4IhLgPIAAhVIE5AAQB8gBBGAxQBFAwAABgQAAAygaAmQgaAmgxATQA/AOAhAtQAfAsAAA6QAABmhDA0QhDA0h6AAgA69bTICCAAQA4AAAdgYQAegYAAgxQAAgzgZgcQgZgbg2AAIiNAAgA69WnIBmAAQA4AAAegYQAfgXAAgtQAAgwgfgYQgfgWg8AAIhhAAgAUGEFQhXhmgBiaIAAgJQAAiZBYhmQBXhlCPAAQCPAABZBlQBYBmAACZIAAAJQAACahYBmQhZBkiOAAQiPAAhYhkgAVoi3QgsBEgBBuIAAAKQAABvAtBEQAsBEBZAAQBZAAAthEQAthEAAhvIAAgKQAAhtgthEQguhEhZAAQhZgBgrBEgA7eEHQhbhiABiaIAAgVQAAiZBahjQBZhiCPAAQBSAABCAeQBBAdAsAxIAACLIhqAAIgOheQgVgUgfgNQgggLgsAAQhbAAgxBCQgyBCAABsIAAAWQAABsAxBDQAyBDBZAAQAqABAjgMQAigNATgVIAOhdIBqAAIAACLQgrAxhCAeQhCAchSAAQiOAAhahigAH/FgIAAhVIBLgOIAAn3IhLgPIAAhVIE8AAQCCAABUBTQBTBSAACAIAABzQAACBhTBTQhUBRiCABgALXDzIBdAAQBMAAArgzQAsgzgBhTIAAh0QABhRgsg0QgrgyhMAAIhdAAgAAHFgIkanYIgDAAIAAF1IBLAOIAABVIkjAAIAAhVIBLgOIAAn3IhLgPIAAhVIDYAAIEbHXIACAAIAAlzIhJgPIAAhVIEhAAIAABVIhLAPIAAJagAsMFgIAAhVIAxgJIgfhgIjkAAIgfBgIAxAJIAABVIjwAAIAAhVIAygHIDWpiICRAAIDUJiIAzAHIAABVgAu9A5ICiAAIhQj1IgDAAgAC3x+IAAhVIBLgOIAAn5IhLgPIAAhVIIsAAIAADAIhtAAIgGhTIjhAAIAACwIDuAAIAABtIjuAAIAADJIDkAAIAFhUIBsAAIAADBgAi8x+IiBnRIgEAAIiBHRIiDAAIiPpkIg6gHIAAhVIEEAAIAABVIhAALIBQGBIADABICEniIBoAAICFHiIACgBIBRmBIhBgLIAAhVIECAAIAABVIg7AHIiMJkg");
	this.shape.setTransform(982.5,797.7);

	// text
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#315175").s().p("Eg7pA0bMA7pho1MA7qBo1g");
	this.shape_1.setTransform(984.6,707.5);

	// Layer 5
	this.instance = new lib.step("synched",0);
	this.instance.setTransform(959.1,408.2,0.323,1,0,0,0,3,14.9);

	this.instance_1 = new lib.step("synched",0);
	this.instance_1.setTransform(938.9,436.8,0.585,1,0,0,0,0,14.9);

	this.instance_2 = new lib.step("synched",0);
	this.instance_2.setTransform(920.3,466.5,0.509,1,0,0,0,0,14.9);

	this.instance_3 = new lib.step("synched",0);
	this.instance_3.setTransform(962.7,496.2,1,1,0,0,0,57.9,14.9);

	this.instance_4 = new lib.step("synched",0);
	this.instance_4.setTransform(945.7,525.7,1,1,0,0,0,57.9,14.9);

	this.instance_5 = new lib.step("synched",0);
	this.instance_5.setTransform(928.4,555.5,1,1,0,0,0,57.9,14.9);

	this.instance_6 = new lib.step("synched",0);
	this.instance_6.setTransform(912.3,585.2,1,1,0,0,0,57.9,14.9);

	this.instance_7 = new lib.step("synched",0);
	this.instance_7.setTransform(896.8,614.9,1,1,0,0,0,57.9,14.9);

	this.instance_8 = new lib.step("synched",0);
	this.instance_8.setTransform(879.8,644.4,1,1,0,0,0,57.9,14.9);

	this.instance_9 = new lib.step("synched",0);
	this.instance_9.setTransform(862.5,674.1,1,1,0,0,0,57.9,14.9);

	this.instance_10 = new lib.step("synched",0);
	this.instance_10.setTransform(846.1,702.8,1,1,0,0,0,57.9,14.9);

	this.instance_11 = new lib.step("synched",0);
	this.instance_11.setTransform(830.6,732.5,1,1,0,0,0,57.9,14.9);

	this.instance_12 = new lib.step("synched",0);
	this.instance_12.setTransform(813.6,762,1,1,0,0,0,57.9,14.9);

	this.instance_13 = new lib.step("synched",0);
	this.instance_13.setTransform(796.3,791.8,1,1,0,0,0,57.9,14.9);

	this.instance_14 = new lib.step("synched",0);
	this.instance_14.setTransform(778.7,821.5,1,1,0,0,0,57.9,14.9);

	this.instance_15 = new lib.step("synched",0);
	this.instance_15.setTransform(762,849.7,1,1,0,0,0,57.9,14.9);

	this.instance_16 = new lib.step("synched",0);
	this.instance_16.setTransform(743.9,879.4,1,1,0,0,0,57.9,14.9);

	this.instance_17 = new lib.step("synched",0);
	this.instance_17.setTransform(728.1,909.1,1,1,0,0,0,57.9,14.9);

	this.instance_18 = new lib.step("synched",0);
	this.instance_18.setTransform(710.4,938.8,1,1,0,0,0,57.9,14.9);

	this.instance_19 = new lib.step("synched",0);
	this.instance_19.setTransform(694.9,968.5,1,1,0,0,0,57.9,14.9);

	this.instance_20 = new lib.step("synched",0);
	this.instance_20.setTransform(677.9,998,1,1,0,0,0,57.9,14.9);

	this.instance_21 = new lib.step("synched",0);
	this.instance_21.setTransform(660.6,1027.7,1,1,0,0,0,57.9,14.9);

	// column
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FEFEFE").ss(1,0,0,4).p("AmRjWQDwhLCfgDQC0gDDgBRIAAH7IsjAAg");
	this.shape_2.setTransform(985,403.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FEFEFE").s().p("AmRElIAAn7QDwhLCfgDQC0gDDgBRIAAH7g");
	this.shape_3.setTransform(985,403.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E4E4E4").s().p("AqXCFQkeg8AAhOQAAhQEeg2QEYg2GJAAQGFAAETA5QEUA5gBBPQABBQkUA5QkTA5mFAAQmDAAkeg9g");
	this.shape_4.setTransform(985,376.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FEFEFE").ss(1,0,0,4).p("AGSDXQjwBLifADQi1ADjfhRIAAn7IMjAAg");
	this.shape_5.setTransform(985,960.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FEFEFE").s().p("AmRDXIAAn7IMjAAIAAH7QjvBLigADIgNAAQixAAjWhOg");
	this.shape_6.setTransform(985,960.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E4E4E4").s().p("AqhCJQkUg5AAhQQAAhPEUg5QETg5GGAAQGCAAEfA9QEcA8AABOQAABQkcA2QkYA2mJAAQmGAAkTg5g");
	this.shape_7.setTransform(985,988);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FEFEFE").ss(1,0,0,4).p("EAOyg0bIAAD9QgzAmheAPQi6AejVhwMAACBdfIA4AEQBGAHBEANQDcAsB/BfIgHFUQjxCGl2AwQh1APh1AEIhbACQkkgPiMgYQkDgsj0h4IgIlUQCAhfDdguQBugWBVgEMAAAhadQkAgqhQgbQg/gWiRhZIAAkNQGei2I/AQQEGAIDrA0QDvA0CmBZg");
	this.shape_8.setTransform(984.7,686.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FEFEFE").s().p("EgGyA2/QkDgsj0h4IgIlUQCAhfDdguQBugWBVgEMAAAhadQkAgqhQgbQg/gWiRhZIAAkNQGei2I/AQQEGAIDrA0QDvA0CmBZIAAD9QgzAmheAPQi6AejVhwMAACBdfIA4AEQBGAHBEANQDcAsB/BfIgHFUQjxCGl2AwQh1APh1AEIhbACQkkgPiMgYg");
	this.shape_9.setTransform(984.7,686.7);

	// Layer 11
	this.instance_22 = new lib.guy();
	this.instance_22.setTransform(968.9,182.1,1,1,0,0,0,35.1,99.8);

	// Layer 9
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#C8DDE0").s().p("EiV/AXEMAAAgsWIZkDPQVohzWAhxUAsCgDiAB/AALUACBAALAyzABKQZbAlZAAiMBRYgCcMAAKAwrQkugSlZgQQqwghjNAGUgDMAAGg1KgA+Mg0hgA/MhxoAEGg");
	this.shape_10.setTransform(960,421.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#B5C6CB").s().p("EiV/gP0MApaAB/UADtAAMBCSgDIUBEtgDQAEugAEUAIQgAHAqRABTUApyABRAFYAAfQETAYG9hoQDegzCng5MAAKAlIMkr+ADDg");
	this.shape_11.setTransform(960,655.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#666E74").s().p("EiWsAbFMAAAgzMMAw2gC9MDe8ACUIdmiUMAAAA2Jg");
	this.shape_12.setTransform(956.5,906.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#BDDDE6").s().p("EiV/ga3MEr0AAAMAAKAwqMkr+AFEg");
	this.shape_13.setTransform(960,172);

	this.addChild(this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.instance_22,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.instance_21,this.instance_20,this.instance_19,this.instance_18,this.instance_17,this.instance_16,this.instance_15,this.instance_14,this.instance_13,this.instance_12,this.instance_11,this.instance_10,this.instance_9,this.instance_8,this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(952,540,1929,1080);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;