(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1920,
	height: 1080,
	fps: 60,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Path = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgjNAJ3Qh/hvBNi6QAmhQAGgYQALglgwAIQiJAWl7gfQhsgJllgnQiKgOjFhKQjYhOhdhXQhxhoB4hMQCRhbHWglQGbggNginIKRh/QFjhCDWgcQAegEJuAYIJnAYIFhAAQDaABB2AMQFJAhk4B/QEqhQEkAjQCSARBgAiQGNAsHhgSQEKgKGhggQEsgRBKApQBbAziNCrQhfBzlACoQkzCfmpCkQmyCnmqB3QnNCBlUAoQ1JCisyAAQuhAAjtjQg");
	this.shape.setTransform(397.7,83.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,795.6,167.9);


(lib.ColumnGuy = function() {
	this.initialize();

	// flash0.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AABAPIgBgCIgEgEIAAgBIADgCQABgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAgBAAIgDABIgBABIAAgCIgEgFIgBgCIABgDQACgEADgBQAFgDADAEIADAFQABACgBAEIgBACQAAABAAAAQABAAAAABQAAAAABABQAAAAABABIAEADIgBADQgBADgEABIgDAAg");
	this.shape.setTransform(40.9,124.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgZAXIgCgFIgBgIQAAgDACgEQACgDAGgBIAHgFIAFgHQADgGADgCQADgDAGgBIAHABIAGADQADACADAGIABAIIgBAFIgCADIgCAAIgDgDIgIgDIgDAAIAAAAIgBgBIgEAAIgFAAQgEAAgDADQgCABAAADIAAAHQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAABIgDADIgCAEIgBABg");
	this.shape_1.setTransform(43.9,143);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgCAIIADgPIABgBIAAABIgBAGIABgCIABgEIAAABIgDAOIAAgDIgCAFg");
	this.shape_2.setTransform(39.6,123.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAKASIgDgBIgDgCIgCgCIgBgCIABgEQABgBAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAAAIgIAAQgDAAgCgBIgEgJIAAgCIACgDQAEgDAEAAQAFgBACADIAEAEIACAGQAAAEABABQABAAADABIAGADIABAEIgBAFIgBADIgEACg");
	this.shape_3.setTransform(28.8,131);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgYBOQAIgKALgKIAagWQACgDABgFIgBgJQgBgHgCgFQgFgJgJgLIgIgKIgLgIQgHgGgKgPQgIgPgEgKIADgBQAJAEANAMQANAOAEAHIAEAMIAHAMQAFAHANAKQAFAFAFAIQADAHABAJQAAALgFAHQgDAFgJAIIgDACIgWAKQgNAFgLADg");
	this.shape_4.setTransform(39.9,132.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AFjKvQgNgCgJgFQgKgFgIgHQgKgIgFgIIgMgRQgOgYgYgtQgVgogyhlIgJgSIgJgQIgKgOIgNgNQgbgWgogIQghgGgpAAQgdABgwAFIhOAJQguAFgiAAQgYgBgRgEQgYgFgQgMQgOgKgMgXQgJgRgHgVQgMgnABgqQABgPAEgZIAGgmQAJhOgGhMQgGhQgShIQgagRgUgPQgagWgQgSQgtgzgNgyQgIgeAFgcQAEgeATgYQAQgWAcgQQAXgOAegKQAfgJAagDIAOgDIAPAAQANAAAQAGQAZAKAVAaQARAUAMAeQAXA3gEA7QgDA7gcArIACgBQAGgCAFgEIAWgPIAogkQAUgSA5g4ICYiXQA1gxAcgXQAXgSAUgPQAdgUATgIQASgHANABQAJABAHAGQAIAHADAIQAEANgGATQgFAOgIAMQgOAVgUAXIglAnQggAggvAqIhQBIIhNBJQg3A1gUAXQgUAYgLATQgIAPgCAIIgCAGIAAAGIABAMQAFAkANBGQAKA/AAArQABA2gPAzQA8gHARgBQArgBAiAGQAjAFAqAOQAYAHAyATQAUAGAPAQQALALAOAUQAQAYAUAvIAeBJQASAuAMAbIARAiIASAcIACABQADACAJgDQAJgCAIgFIAkgRQAZgKARABQAZAAAQATQAJAKACALQACAMgFANQgHAPgUASQgbAXgpAVQgRAJgUAIQgNAGgHABIgOABIgJAAgABLE6QAtAIAfAaIAPAPIANARIATAkIBGCMIAlBFQAGAJAFAGQAEAGAIAHIAOAJQAHAEAJABQAGABAKgCIARgFIAjgQQAogUAYgVQASgPAFgMQAHgOgMgMQgLgNgRgBQgMAAgWAIIgjARIgUAHQgHACgFAAQgHABgHgEIgFgFIgJgNQgGgHgFgKQgKgSgHgSQgMgagSgvIgchKQgQgogRgeQgagogcgKIhKgbQgqgPghgGQgjgIgpABQghACgtAFIgCAAIABgCQAMgxgBg5QgBgogMhAQgPhGgFgkIgCgOIACgPQADgKAIgQQALgUAVgZQAhgmApgoQAfggAugqQB6hvAjgkQAxgzATgdQAIgNADgKQAFgMgDgIIgFgHQgDgDgFgBQgJAAgMAFQgSAIgbASQgUAOgWATQggAZgwAtIibCUIhPBKQgXAUgSAOIgWAQIgNAHIgHACQgFABgFgCIgFgCIAEgEQAggsAEg9QAEg6gWg1QgMgdgQgUQgUgZgYgJQgPgGgMAAIgNABIgOACQgbAEgdAJQgaAIgZAPQgbAPgPAVQgSAXgEAcQgEAaAIAdQAOAxArAvQASATAYATQASAOAdASIACABIAAADQAUBIAHBUQAIBOgIBOQgBANgEAbQgEAZAAANQgCAkAMAmQAHAVAIAOIAKAPIAAABIAGAGIAGAFQAOALASADQAPADAWABQAgAAAtgFIBOgKQA1gFAbgBIANAAQAkAAAdAGg");
	this.shape_5.setTransform(71.6,175.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FEFEFE").s().p("AFUKfQgXgLgSggQgegzgjhHIg1hrQgeg8hMgPQg1gLhhALQiBAOgVAAQhKABgYgiQgVgbgKgpQgLgvAIgrQAVh1gRiEIgVhwQhIgrgog5Qgpg4ABg0QAAg4AtglQAygpBegMQAogFAiAfQAgAdAQAzQARA0gFA1QgGA5geApQAPAIBMhFICfibQDqjiAnAbQAiAWg8BJQgoAxhzBnQiCB4gnAoQhPBTAEAkQAFAqAVBrQAOBpgVBLQBdgLAwAGQA4AIBwArQAvASAzCAQA9CbAXAdQAHAKATgHIAogSQA6gcAbAhQAZAfg5AqQgoAeg5AXQgNAFgLAAQgOAAgNgHg");
	this.shape_6.setTransform(71.3,175.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FEFEFE").ss(1,0,0,4).p("AmRjWQDwhLCfgDQC0gDDgBRIAAH7IsjAAg");
	this.shape_7.setTransform(95,104.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FEFEFE").s().p("AmRElIAAn7QDwhLCfgDQC0gDDgBRIAAH7g");
	this.shape_8.setTransform(95,104.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E4E4E4").s().p("AqYCFQkdg8AAhOQAAhQEdg2QEZg2GIAAQGGAAETA5QEUA5AABPQAABQkUA5QkTA5mGAAQmCAAkfg9g");
	this.shape_9.setTransform(95,77.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#FEFEFE").ss(1,0,0,4).p("AGSDXQjwBLifADQi1ADjfhRIAAn7IMjAAg");
	this.shape_10.setTransform(95,662);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FEFEFE").s().p("AmRDXIAAn7IMjAAIAAH7QjwBLifADIgNAAQixAAjWhOg");
	this.shape_11.setTransform(95,662);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E4E4E4").s().p("AqhCJQkUg5AAhQQAAhPEUg5QEUg5GFAAQGCAAEfA9QEdA8AABOQAABQkdA2QkYA2mJAAQmFAAkUg5g");
	this.shape_12.setTransform(95,689.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FEFEFE").ss(1,0,0,4).p("EAOyg0bIAAD9QgzAmheAPQi6AejVhwMAACBdfIA4AEQBGAHBEANQDcAsB/BfIgHFUQjxCGl2AwQi7AYiKgDQkkgPiMgYQkDgsj0h4IgIlUQCAhfDdguQBugWBVgEMAAAhadQkAgqhQgbQg/gWiRhZIAAkNQGei2I/AQQEGAIDrA0QDvA0CmBZg");
	this.shape_13.setTransform(94.8,387.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FEFEFE").s().p("EgACA3mQkkgPiMgYQkDgsj0h4IgIlUQCAhfDdguQBugWBVgEMAAAhadQkAgqhQgbQg/gWiRhZIAAkNQGei2I/AQQEGAIDrA0QDvA0CmBZIAAD9QgzAmheAPQi6AejVhwMAACBdfIA4AEQBGAHBEANQDcAsB/BfIgHFUQjxCGl2AwQimAViBAAIgeAAg");
	this.shape_14.setTransform(94.8,387.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#D7D1C2").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIgBAAIAAAAg");
	this.shape_15.setTransform(47.9,42.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#BDAEA1").s().p("AioBLIAHgDIAXgMQAEgCADgFQAFgIACgJIAFgUIACgWQABgOgBgGIgBgcIgCgTIABgDIACARQACAPABALIAAARQABAMgDAKIgEAWIgHAVIgEAHQADABAEgCIAEgBQAMgEAEgIIAIgWIAEgYIgCg1IgBgLIABgBQABABAAAGIADATIABAPQAAAPgCATQgCAPgFANIgGAMIgBAFIAIgEIAKgDIAQgHIAcgKIAsgSIASgHIAIgCIANgDIAWgIIAQgFIAvgRQADgBAHgDQAKgCARgHIAIgDIgDADIkcBqIgGABQgEAAgFACIgSAIIAAAAIgJACIgJADIgBABIABgCg");
	this.shape_16.setTransform(56.7,52.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#C9C1B3").s().p("AADADQgDgCgEgDQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAAACQACABAEACIABACg");
	this.shape_17.setTransform(157.1,24.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D7D1C2").s().p("AAEAEQgCgDgCAAIAAAAIgHgFQgBAAAAAAQAAgBgBAAQAAAAAAgBQABAAAAAAIAHgCIgCACIAEAFQAGABACAIIAAABg");
	this.shape_18.setTransform(157.7,25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#C9C1B3").s().p("AjLA7IgBgBIgCAAQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAGgCAEgCIAFgCIAQgFIAKgDIADgBIAFgCQAMgDADgCQAHgDAIgBIADgBIAQgFQAGgBACgBIABgBQADABAHgCIABAAQAGgEAPgDIAVgFIANgDQAGgBAMgDIAhgHIAGgCIAIgBIAKgDIAFgBIACAAIAUgFIAkgIIAagGIA3gPIAHgBIAGgCQAAgBABAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgDgDQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQAFAEACADIAAACIgCACQgNACgOAEIgVAFIgXAGIhoAXIgTAEQgLACgFABIgQAEIiQAnIgIADIgZAIQgEABAAADg");
	this.shape_19.setTransform(137.9,31.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#91091E").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIAAABg");
	this.shape_20.setTransform(106.4,32.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#91091E").s().p("AAAABIgBgBIABAAIACABIgCAAIAAAAg");
	this.shape_21.setTransform(104.2,50.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#91091E").s().p("AgBAAIADAAIgBAAIgBAAIgBAAg");
	this.shape_22.setTransform(104.5,49.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#91091E").s().p("AgBAAIAAAAIABAAIADAAIAAABg");
	this.shape_23.setTransform(104.3,49.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#E3DED2").s().p("AAAAAIACAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAgBAAIgCABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAg");
	this.shape_24.setTransform(129.6,33.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#E3DED2").s().p("AgCAAQABAAAFAAIgCAAIgDABIgBAAIAAgBg");
	this.shape_25.setTransform(144.2,30);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#E3DED2").s().p("AgCAAIAJgBQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAIgMACQAAAAABgBQAAgBAAAAQABAAAAAAQABAAABAAg");
	this.shape_26.setTransform(142.8,30.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#E3DED2").s().p("AgIABIANgCIAJgBIgBABIgaAEQABgCAEAAg");
	this.shape_27.setTransform(139.7,31.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#E3DED2").s().p("Ag1AQQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAABgBIAZgJIARgEIA+gRQAAABAAAAQAAAAgBABQAAAAgBAAQgBABgBAAIgbAHIgIADIgDABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgDABIgOADIgZAIQgHAEgEAAQgEAAAAAEg");
	this.shape_28.setTransform(123.5,35.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#D7D1C2").s().p("AjNA3QgCgEAFgBIAugPIA0gPICRgjIAlgIIAwgLIAlgJQAWgGAOgDQACAAACgDIACABQABABAAABQAAAAAAABQABAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgIABgEABIgTAFIgWAFIgEABIgZAGIgNADIgrAJIgBACIgCAAIgIACIgCAAIgJADIgFACIgDAAIgDABIgEAAIggAHIgSAEIgPADIgLADIgCABIgCAAIgFACIgCgBIgCACIgCAAIgSAFIgCAAQgEAAgCACIgCAAIgNAEIhHAVIgaAKIAAAAIgEgBg");
	this.shape_29.setTransform(138.3,31.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#E3DED2").s().p("AgBAAIADAAIgBABQgBAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_30.setTransform(36.5,62.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#E3DED2").s().p("AgBAAIABAAIADAAIAAABQgEgBAAAAg");
	this.shape_31.setTransform(37.6,63.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#D7D1C2").s().p("AAeAwIgNgOQgNgMgJgPIgPgRIgBgBIgIgMQgEgEgDgIQgDgIACgFQABgEABAAIACABQABAGADAEQgCADACAFIAKASIAJAOQAFAGAKAOQAEAGAOANQAGAHAGAEIADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABQgDgCgGgEg");
	this.shape_32.setTransform(32.2,57.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#C9C1B3").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIgBABIAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_33.setTransform(25.5,36.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#E3DED2").s().p("ABsgjIjXBIg");
	this.shape_34.setTransform(80.3,47.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#E3DED2").s().p("AkVBmQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAQAKgBAMgFIAVgIIBXgkQAOgFAbgNIA1gUIBPgbIgsARIgJADIgEACIgVAIIgTAIIgCABQgEAAgFADIgGADIgGACIgYAKQgOAFgGAEIgEABQgFABgKAFIgLAEQgHAEgQAGIg6AYQgLAEgNACgAAxgWIAGgDIAJgDQAIgDAMgEIARgGIABgBQACgCAFgBIB0gmIAGgBIAvgRIgBAEQgKABgIADIgNAEIgPAFIi3A/g");
	this.shape_35.setTransform(66.6,53.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#C9C1B3").s().p("AkdCeQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAABAAIAFgJQAGgLABgEIAAgCIABgCQAFgRABgSQACgUgBgQIgDgmIgDgRIgBgBIgBgFQAGABADgEQAAAAABgBQABAAAAAAQABAAAAAAQABABAAAAQADACAEAAQACgDAEAAQAFAAACgEQAEgCgBgGIgBgIQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIACAQQACAMAEAAIAFgCIAIgGQADgBABgCQACgEgBgCQAFAGALgDIAkgMIAlgGQAJgBAGgDIAIgDQAEgCADAAQADAAAFADQAEAAAIgEIALgEIAbgEIAcgHICBgjIBlgfIAQgHIAHgEIAJgDIAKgEQANgHAIgJIgCAJIgFAKQgJANgVASIghAbQgUAUgJARIgJAUQgFAKgKAEIgeALIgYAJIgmANIgDADIgFACIgCABIgEAAIhcAiIgjAMIiRA3IgDAAQgCgCACgDQgDAGgIACIgKADQgDACgCgCQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAFgKIgEAJQgFAIgIAEIgbAOIgBAAIgCAAIgBAAgAjPBmIABgHIABgEIgCALgAjLA9IAAAQIAAgMIAAgEIAAgUIgBgKIABAeg");
	this.shape_36.setTransform(67.9,44);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#998877").s().p("AAAAAIABAAIAAAAIgBAAg");
	this.shape_37.setTransform(93,17.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#D42939").s().p("AAAAAIAAAAIABAAg");
	this.shape_38.setTransform(92.7,16.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#D7D1C2").s().p("AAAAAIABAAIAAABQgBAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_39.setTransform(34.6,28.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#E9E6DA").s().p("AAAAAIAAAAIABAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAgBg");
	this.shape_40.setTransform(65.7,32.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#998877").s().p("AgCAAIAAAAIAFAAIgDAAIgCAAg");
	this.shape_41.setTransform(91.7,16.9);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#BDAEA1").s().p("AADARQgDgXgEgLIAAgDQACACABAFIACAQIAEASQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAgBg");
	this.shape_42.setTransform(39.9,41.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#C9C1B3").s().p("AAJAaIgPgtIgCgFQgBAAAAgBQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAIAZIAJAZIABAEQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBg");
	this.shape_43.setTransform(38.2,35.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#E9E6DA").s().p("AAPAuQgFgFgBgDIgFgOQgFgSgFgHIgMgUQgEgIgGgIQgDgEAAgFQAEgBADABQACABAEgBQAGADADAGIABABQAFAGAHAOIACABIAFAJIADAEIADAFQAAACACAFIAMAcQAAAAAAABQABAAAAABQAAAAAAABQAAABgBAAIAAAFQgDAAgCgDIgCAAQgCADgEAAIgCAAIgBgBg");
	this.shape_44.setTransform(41.7,32.4);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#E9E6DA").s().p("AAIAvQgDgEgEAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAQgKgfgFgJIAAAAIgBgBIgBgCIgBgCIgBgCIgBgCIgKgRIgCgCIgHgLIAAgCIACgCIAEAAQAEgDAGAAIACgBIAIgDIAJAFIAFAJQAGAHAGAKIAWAuIAFAPQgBACgFgCQAAAAgBABQAAAAAAAAQAAAAAAAAQAAAAAAABIAAABQAAAAgBABQAAAAAAAAQgBAAAAAAQAAgBgBAAIgDABQgEgCgDADIgDACIgFACQgCAAgCgEg");
	this.shape_45.setTransform(38.7,32.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#BDAEA1").s().p("AhtCDIAUgHQA7gVAOgIQAMgGAEgKIACgPIAFgIQACgFADgCQAFgEABgEQADgEADgBQACgBADgEQAFgIANgKIAGgGIABAAQABgEAEgDIAHgDIALgIIANgNIAGgGQACgDABgGIAEgIIABgBQAAgCACgGQAEgJABgKIABgKIABgSIgBgUIgBgLIACACIAAAAIABABIAAAhQAAAPgBAOIAAABIgDAYIgCAGIgIAbQgBADgDAEIgCADQgBACgDAGIgBABIgEAHIgEAHIgCAFQgEAJgDACIgBADIgDAJIgCAIIAAABIABADQgEAKgIADIgGADIgGADIgBABQgCACgKADIhRAcIgSAGIgWAIIgTAFIgDAAQAAAAAAAAQAAgBABAAQAAgBABAAQABgBABAAg");
	this.shape_46.setTransform(86.2,33.3);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#E3DED2").s().p("AjrBbQgEAAgBgFIgDgSQAAAFgBADQgCAEgHACQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgDADgGgCQgCgCgEACQgEADgDgCIAAgBIgGgYQgCgIAAgEQACAAADADIAEgBQADgBABgCQACgBADAAIAGABIAEgDIACgEQAAAAABAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABABAAQAAABAAAAQABAAAAAAQABAAAAgBQgCgJAAgFIAFANIAEAOQAEADAEgEQACABAFgCQABgBAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgBQACgCgBgDIgCgGIgBgHQACABABAEIABAFQABADADADIALgDIADABQADABACgDIAEgEQABAAAAAAQABAAAAABQABAAABAAQAAABABAAIAKgEIACACQAAAAAAAAQABAAAAgBQAAAAABAAQAAgBABAAQACABADgBIALgCIADAAIACAAIAJgBIACgFQAFgBACgCIAEACQADABACgCQACgDAEABIADABQAEAAABgDQAAAAAAAAQABAAAAABQABAAAAAAQABAAABABIADgCIAAgCQgBAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAgBQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAEABQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAgBIAJgDQAEgBADACQADAAACgDQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAAAIADgCIALgBQADgBACADQACAAADgFQACgCAGAAIACgDIAGACIACgCQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIAFAAIADABQAAABAAAAQAAAAABAAQAAABAAAAQABAAAAgBQABgCAEgCIAEgBQADAAADABIAEAAQAEAAAAgBQACgCAFAAIACgDQADgBADACQAGAEAFgFQACgEAEACIABAAIAEgBIACAAIACgEQAAAAAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAQAAAAABAAQgBgBAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAEAEAEgDIAEABQAIgFABgFIACADQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABAAQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBQAHgCAEACQADAAADgDQADgEAFADQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAABgBIADACIAFgBQABAAAAAAQABgBAAAAQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAAAABgBIAFgCQADgCACABQAAAAABAAQAAAAABAAQAAAAAAgBQAAAAABgBIABABIABACQAGAAAFgEIAFgBQADgBACgDIALgCQACgCAHgBQAAAAABAAQAAAAAAABQABAAAAAAQABABAAAAQADgEAFgBIAKgBIABAAQABAAAAAAQABABAAAAQABgBAAAAQABAAAAgBQAEgEAGAAQAFABAEgEQABgBAEgBQAFABACAAIAFgFQAGABALgFIACABIABABIADgCIAEgBIAFgGIAGgCIAEgEIACgCQACgFAEgBQABADgBAFQgBAGgFAMIgSAPQgHAFgDgBQgBAAgBABQAAAAgBAAQAAAAAAABQgBAAAAABQgCAEgEgDQgDgCgCADQgBAEgJAEQgFABgBACQgCABgEgBQgEgCgDADIgKADIgBADQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgFAFgFgDQAAAAgBAAQAAgBAAAAQgBAAAAABQAAAAgBAAQgHACgDADQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQgDgBgCADQgCAEgBAAQgCAAgDgEQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBABQgHAGgKgBQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAAAIgEAEQgHgDgBADQgKAAgGACIgCABQgDAAgIADQgHADgFgBIgCADIgCAAIgDgBQAAABAAABQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBIgFAAIgEAAQgFACgCgCQgBAGgIgBIgDABQgEAFgGgDQgCAEgDAAQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgFADgFgBIAAAAQgCgBgEACQgCABgCgBQgCgCgIAGIgDABQgIAAgDACQgDACgFgCQAAABAAABQAAAAABABQAAAAAAABQAAAAAAABQgCAFgEgEQgFgEgIADIgGADQgEABgEgBQAAAAAAAAQgBgBAAAAQAAAAAAABQgBAAAAAAIgLADIgFADQgDAFgFgDQgJgGgHAHQgCADgGgBQgLAAgGAFQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAgBIgGgBQgEgBgBgCIgCABQgDAFgEgBQgGgBgDAFQgCAEgEgDQgDgCgGACQgDACgEgBQABADgCACQgHgCgEACIgEAAQgGAAgCADQgFAAgCgFIABADQABAHgHACQgDAAgFAFQAAABgBAAQAAABgBAAQAAAAAAAAQgBABAAAAIgBgBg");
	this.shape_47.setTransform(68.5,34.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#998877").s().p("AAyCWQgDgEgBgEIgBgCQgHgHgDgIIAAgBIgDAAIAAgBQABgCgCgDIgDgDIgHgKIgEgFIgHgKIgEgHIgGgLIgCgCQAAgDgDgDQgCgDgBgFIgBgDQgDgFgDgCIgBAAIgFgJIgEgIQgDgFAAgEIgCgCQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBgEgCgCIgBgBQgEgIgBgDQgCgGAAgDIgBgDQgDgEgBgDIgDgFIgCgLIgDgJIgCgGQAAgGgCgDIgCgDQgBgFADgCIgCgCIACgEQADgFgCgGIAAgBQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIgBgEQAAgFACgEIABgGQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAEgCACgGIAEABQAEgCADgEIAGgIIAFgDQAEgGABAAIADgDIABAAIACACIAEAEIALAMIAIANIAJARIACACIAAACIACAEIACACIAAABIAMAdIAIAZIACAFIAAACQAGAQAEAVIABADIABABIABAKQAHAhAAAhQgBAigFATIgBAFIgCADIgBABIgDACIgBgBg");
	this.shape_48.setTransform(34.9,42.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#E9E6DA").s().p("AjkBYQgEAAgDABQgEgDgDgHIgLgXIgBgCIAAAAIgDgFIgBgBIgCgEIgFgJQgBgEgGgIIgIgMIgDgEQgDgDACgDQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIACABIAOgCQAGAAACAAQACgBADABIADgBIACABQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAAAAIAFgCIACgCIAFgBIAGAAQACABAGgBIADgDQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAIADACQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABABIADADIABgEIADAAIACABQAJgBABABQADgBABgEQAGgCADABQAFACADgDIAIADIACgEQAFABACgDQAEgBACAEIAJgEIAEABIADgCQABAAAAAAQABAAAAAAQABAAAAAAQABABABAAQAAAAAAAAQABgBAAAAQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQABAAAAAAIAEgBIAEAAIAFgBQAAAAABAAQABAAAAAAQABgBAAAAQAAAAABgBQABABAAAAQABAAABAAQAAAAABAAQAAAAAAAAIADABIACAAQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIADgBQADAAAJgCIADgBIAEgCQAEgBADADIABABQAHgDAJgCIALgBIACAAQACgEAEACIADACIAEgDQACgBADACIAEgCIAEAAIADgBQADABAKgEQAGgEAGACQAAAAABAAQAAAAABAAQAAgBAAAAQABAAAAAAQADgEAEABIAKgBIAIAAIAEgDIADACQADAAACgCQACgBAJABIAHgEQADgBAFAAQAGAAADgDIABAAQAJAGAIgHIADAAIAEgDIAIABIADgCIAGgBIAEAAQAEABAEgCQADgDADABQAIADAKgHIABAAQACABAEAAIAFgCIACgBQAFgDAGACQADABAFgEIAFACQAEAAADAAIADAAIADgCQACABAGgDIADABQABAAAAgBQABAAAAAAQABAAAAAAQAAgBABAAIADABQAEgCACAAIADgCQAJAHAGgCIAKAIIADADQACAEgBAIIABAEQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBABQAAAAAAABQAAAAAAABIABAEQgBADgCABIAAAEQAAADgGABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABIgCADIgFAAIgGACIgBAAQgDAAgDAFIgBAAQgFgEgCAEIgDgBQgEAAgEADIgGAEIgFgBIgEgCIgCACIgDgBQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAABIgCADQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIgCgBQgDABgEAFIgCgCQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQgDAEgDABIgDgCIgFABQgCABgBADQgFAAgCABIgGABIgHgBIgDACIgDADQgEAAgCgCQgGAGgFABQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgHAFgCADIgLAAIgDADIgBAAIgCgBIgHACQgHACgEgBIgEACQgEACgFAAIgJADQgEgBgEACIgFAGIgGgBQgCgCgDABIgCACQgFADgDgCQgDAAgDABIgCABIgHACQgFACgCgBQgCADgDAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQgCAFgEgCIgCAAQgDACgGgCIgDACIgFAAQAAABgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBIgKAAQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAQgDgDgCABIgBABQABAFgFgCIgJAAIgDADIgEACQAAgBAAgBQgBAAAAgBQAAAAgBAAQAAAAAAgBIgGAAIgEAEQAAgBgBgBQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAAAIgDAAIgCAAIgDACQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBIgDADQgEgBgCABIgBABIgHABIgGAEQgFgCgEgFIAAAFIgDACIgDgBQgEAAgCABQgHgBgBgCQgBADgCABQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAIgEADIgEgBIAAAAQgEACgDgDIgEgCIgCAFQgEgBgDADIgPACIgGADQgEABgDgBIgDADIgEgBIgCABQgCACgEAAIgHgBg");
	this.shape_49.setTransform(69,27.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#C9C1B3").s().p("AAAAAIAAAAIAAAAIAAAAIAAAAg");
	this.shape_50.setTransform(109.1,40.6);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#D42939").s().p("AAAAAIAAAAIAAAAg");
	this.shape_51.setTransform(104,49.5);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#D42939").s().p("AAAABQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAABg");
	this.shape_52.setTransform(124.5,45.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#C9C1B3").s().p("AAAAAIgBAAIAAAAQABAAACAAIgBAAIgBAAg");
	this.shape_53.setTransform(109.9,40.8);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#D42939").s().p("AAAAAIAAAAIABAAIAAABQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAAAg");
	this.shape_54.setTransform(102.3,51.5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#D42939").s().p("AgBAAIABAAIABAAIAAABQgBAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_55.setTransform(104.7,47.7);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#D42939").s().p("AgBAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIACAAIgBABQgBAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_56.setTransform(105.1,45.3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#D42939").s().p("AgBAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIACAAIAAABIgDgBg");
	this.shape_57.setTransform(104.6,48.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#D42939").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAABAAIgDABQAAgBAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAg");
	this.shape_58.setTransform(97.2,31.9);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#BDAEA1").s().p("AAFACIgKgDIABAAIACAAIACABQADAAACABIABABIgBAAg");
	this.shape_59.setTransform(118.1,37.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#D42939").s().p("AgBABQAAAAABAAQAAgBAAAAQAAAAAAAAQAAAAAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAgCIACACIgBADIgCgCg");
	this.shape_60.setTransform(105,45.9);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#D42939").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAIAAABIABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIgBACg");
	this.shape_61.setTransform(125.1,45.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#D42939").s().p("AgGAAQAAAAABAAQAAAAAAgBQAAAAABAAQAAgBABAAIABABIgBAAIADABIAAAAIACAAIABAAIAAAAIAEAAIgBADIgMgDg");
	this.shape_62.setTransform(123.6,45.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#D42939").s().p("AgCAEQACgDAAgBQAAAAAAAAQAAAAAAAAQAAgBAAABQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIAAgCIABAAIACAAIgBAEIgBABIABABIgBADIgDgBg");
	this.shape_63.setTransform(104.4,48.9);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#D42939").s().p("AgCAHQAAgBABAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAAgBQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAABAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQABABAAAAIABgCQgBAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIADAAQgBAHgCAIQAAAAAAAAQAAAAAAAAQgBAAAAgBQgBAAAAAAg");
	this.shape_64.setTransform(105.3,43.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#998877").s().p("AgLgFIAZAHIgCAAQgBgBgHAAIgFABIgMADg");
	this.shape_65.setTransform(107.4,40.2);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#D7D1C2").s().p("AgSAIIABgHQABgBAGgBIATgJIACAAIABABIACABIADAAIABABIABAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgEACQgHABgFADIgFABIgEACIgEADQgDABgBADIgEABg");
	this.shape_66.setTransform(107.7,41.6);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#BDAEA1").s().p("AgSAKQACgEAEgBQADAAAEgEIAEgBQABgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIAKgGQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAABIABAFQgBADgDABIgGADIAIACIAGACQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgLgCIgMACIgMADIgBAAIgBgBg");
	this.shape_67.setTransform(97.4,49.9);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#998877").s().p("AixA7IgjgMIgDgBQAHgLABgPIABgDIAEADIAXgCQAGgCAMACIACABQABABAAAAQABAAAAAAQABAAAAAAQABAAABAAIABAAIAEAFIAHgBQAIAAAPgFICFggIB1gdIBBgPIAGgCIAMgCIACABQABADgDACQgEAHgIACIhJAUIgIABIgEABIghAIIgTAFIgGABIgNADIgVAGIhiAYIgMADIgqAMIgBAAIgRAGIgQAGIgQAHIAJAEIACAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgLgDg");
	this.shape_68.setTransform(134.1,30.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#998877").s().p("AkjCiIgHgEIgDgEIABgBQAJgBAKgFIAEgCQABAAAAAAQABAAAAAAQAAAAABAAQAAgBAAAAIABgBQAMgGAYgIIAEgBQAIgBAKgEIARgIIAbgKIBPgeIAggMIB0grIAKgEIADgBIAIgDIATgGIAkgKIBcgeQALgEAPgKQAHgFAAgHQgBgCACgEIABgHQABgFAGgHQAEgGAFgMQAFgJAJgSIAHgUIADgNQABAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIgDAcIAAABQAAABAAABQAAAAAAAAQAAABAAAAQAAAAgBAAIgFAdQgEAUgFAUIgIAmQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBIgTAFIgkAKIgOAFIgGACIgSAFIgRAEIgbAJIgPAFIgKAEIgKACIgCABIgJAEIgbAJIgCAAIhBAaIgWAJIgXAIIgMAFIgFACIgLAEIgFACQgHAEgEABIgOAEIgWAJIgbALIgXAJIgNAGIgSAHIgWAJIgkAOQgGACgFAAQgIAAgGgEg");
	this.shape_69.setTransform(67.1,45.4);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#E3DED2").s().p("AhEAaIAYgFIA3gNIAkgIIARgCIAEgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgBgBQgDgJgHgEQgEgCgBgCIACgCIADgBIAEAAQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAIAIAHQADADgBADQgCAEACAFIAAABQgCACgDAAIgjAHIgaAGIgdAHIgaAFIgXAEQAAAAABgBQAAAAAAgBQABAAAAAAQABAAABgBg");
	this.shape_70.setTransform(152,26.9);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#BDAEA1").s().p("AjAA/QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBIAWgIICJgoIAYgGIAXgFQAQgEAggIIAfgHIAzgLIAmgMQAJgCAFgGQACgCgBgDQgIAAgDABIgPAEIh3AcIhZAWIhzAdIgNABIgDgBQgKgIgTACIgVACQgFABgBgFIAAgBIAAgGIAAgHIAAgCIgEgXIAAgDQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQABAEADADQAEADAEgBIALAAIACAAQADgCAFgCQAIgDAEAEIAFgCIAEABIACgCIADgBQACgBABgEIAEAEQACACAEAAIABgCQADgBADABIACgBIABgBIAEACIADADIAGgCQADgBADACIgCAEQAAABgBAAQAAABAAABQAAAAAAABQAAAAAAABIAEADQAAACgCABIAAALQADADAGAAQAFgBAEgDQADACAEgBIAHgCIAagGIAHgBIAXgEIAWgFIAAAAQAHgEANgCIA3gOIATgFIAIgBQAKgEAWgEIALgDIAHgCIAmgIIATgFIAFgBIASgEIABACQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHACQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAJAHIABABIADACQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgiAKIkXBCIgaAIIgLAEIgpANQgKAEgEACIgJgCg");
	this.shape_71.setTransform(135.6,30.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#D42939").s().p("AAAAAIAAAAIABABg");
	this.shape_72.setTransform(110.2,21.9);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#D42939").s().p("AAUBKIAEgCQgCgCgEAAQgDAAgBACQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQgEgBgFACIgIACQgMABgMgDIgCgBIgDgDIgDAAQgHAEgEgCQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAIgCgCQgBACgEgBIgBgFIACgYIACgYIAAgCIACgVIgBgfIAAgFIABgDIAAgBIACgBIACgBIgDgBIADgCIABACQAJABASgCIAaAAQARAAAJgDQALgEADABIgBgIIAaAkQgBABgDgEQgCgDgGgCQgGgCgCgDIgBgGQAAgEgBgCQgBAAgBgBQAAAAgBAAQAAAAAAAAQAAAAAAABIACAEIgBADQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQgBABABAFQABAEgCABQAAABAAAAQABAAAAAAQAAABAAAAQABAAAAABIgCAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAigFAzQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIABACIgCABIABABIAAACIAAABIgBAAQABACAAAEQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQADABAAAGIgGgBIgDACIgDABIgDgCg");
	this.shape_73.setTransform(103.6,25.7);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#D42939").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAg");
	this.shape_74.setTransform(111.5,41.2);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#D42939").s().p("AAAAAIAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIgBAAg");
	this.shape_75.setTransform(111.2,41.1);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#BDAEA1").s().p("AAAAAIAAAAIAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_76.setTransform(129.2,47.1);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#E9E6DA").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAAAIABAAIgBAAIAAABg");
	this.shape_77.setTransform(111.3,41.2);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#D7D1C2").s().p("AgCAAQACAAADAAIgDAAg");
	this.shape_78.setTransform(96,13.3);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#998877").s().p("AAAgCIAAADIAAACIAAgFg");
	this.shape_79.setTransform(93.9,15.5);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#D7D1C2").s().p("AgEAAIACAAIAHAAIgFAAIgEAAg");
	this.shape_80.setTransform(103.6,13.4);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#BDAEA1").s().p("AgCAAIACgBIADACIAAAAIgBABQgCgBgCgBg");
	this.shape_81.setTransform(103,52.3);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#998877").s().p("AACAAIABAAIgDABIgDAAQACgBADAAg");
	this.shape_82.setTransform(90,17);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#998877").s().p("AgBABIgDgBIAAgBIABAAIADABQABACADgCIABABIgDABIgDgBg");
	this.shape_83.setTransform(103.9,52.7);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#C9C1B3").s().p("AAMAFIgKgFIgDAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBAAAAAAQgEgBgDAAIgEAAQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAJgBQAAAAAAAAQAAAAABAAQAAAAABABQAAAAABAAQAJAEAIAGIAAAAIgBAAIgCgBg");
	this.shape_84.setTransform(35.6,26.2);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#C9C1B3").s().p("AAOAFQgNgJgPABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIALgCQAAAAAAABQAAAAABAAQAAAAABAAQABAAAAAAQAHADAKAGQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAAIgDgCg");
	this.shape_85.setTransform(37.4,26);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#D42939").s().p("AgUAHQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAigJIACgBIAFgBIAEgBQgHAFgLABIgRAFQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAAAAIgBAAIgBAAIgCAAIgCABIgBAAIgCAAg");
	this.shape_86.setTransform(92.5,16.2);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#C9C1B3").s().p("AgEAWIAFgXIAAgEQgCgEABgFQABgGAFgFIgCAPQgDAOgFAUIgBACIABgEg");
	this.shape_87.setTransform(93.3,48.4);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#D7D1C2").s().p("AgBAGQgGgGgLAAIgDgBIAKgBIANgCIAHgCIAGABIAFABIACAAIAAACQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgMAAIgGAAQgDgBgEABQABABACADQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAIAAABIgBgBg");
	this.shape_88.setTransform(33.1,26.4);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#998877").s().p("AAhAOIhGgbIAJACIAGACQAJABAEADIADABIABABIACAAQABAAACACIAhAIIAEACIABAAIgBAAIAAACIABADIgCAAIgDAAg");
	this.shape_89.setTransform(125.2,46.2);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#D42939").s().p("AAvAQIgEgBIgEgCIgDgBIhVgcIgCgBIAFABIANAEQADACACgCQAAABABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQABABAAAAQABgBAAAAQABAAAAgBIABACQAAABABAAQAAAAAAgBQABAAAAAAQABAAAAgBIABACIADAAQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAQABABAAAAQABAAAAgBQAAAAABAAQAAAAAAgBQABABAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABgBQAAAAAAAAQABAAAAgBIABACQABABAAAAQAAAAABgBQAAAAAAAAQABAAAAgBQAAABABAAQAAAAAAABQAAAAAAAAQgBABAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQABgBAAAAQABAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAABABAAQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBABAAIADABIACAAIACAAIACABIACAAIABACIADgBIADACQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIACAAIABACQAAABABAAQAAAAAAgBQABAAAAAAQABAAAAgBIAAACQABABAAAAQAAAAABAAQAAAAABgBQAAAAABgBIABADQADgDAEADIAAACIACAAIABAAIABABIADAAQABAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAIABgBIACAAIAAADIgBABIgEgCg");
	this.shape_90.setTransform(117.5,43.3);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#D42939").s().p("AAEAQIgFgDIgBgBQgDgCgBgCQgDgCAAgCQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBgBIAAgBQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAABIACgCIABABIACgBIAAAAQAAgCADgBIgCgEIABgDIACgDIAAgCIABAAQADgBACACIgCAQIgBAHIAAAFQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgBAAg");
	this.shape_91.setTransform(103.5,51.2);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#998877").s().p("AgjAGIAAgCQAAgBAAAAQABAAAAAAQAAAAABAAQABAAAAAAIBBgJIgBgBQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAIgSAEQABABADAAIAFADIgEABIg1ACQgBAAgBAAQAAAAgBAAQgBABAAAAQAAABAAAAg");
	this.shape_92.setTransform(131.7,43.4);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#998877").s().p("AATAPQAAgBAAAAQAAAAgBgBQAAAAgBAAQgBgBAAAAQgOgIgGgBIgBgBIgDAAQgDgCgJAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAGgFQADgDgBgEIAOAKIAVAQQAEADAAABIgCABg");
	this.shape_93.setTransform(100.3,50.5);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#C9C1B3").s().p("AgxANQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAABAAIAAACQABABAEgDQAGgFAJgFIAbgNQAAABABAAQAAABAAAAQAAABgBAAQAAABAAABIgFAEQgEAEgDAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAgBABQAVgFAPAEIAEAAQAHABAOAHQAEABAAADIgHgCQgKgFgIgBIgOgCIgXAEIgZAFQgGACgEAAg");
	this.shape_94.setTransform(97.3,50.8);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#D42939").s().p("AA1AEQgBgEgEAAQgDAAgFAAIgFAAIgJgBIgEABIgJAAIgBAAIgGAAQgEAAgCgBIgBABIgDgBIgDABIgLAAIgCgBIgBABIgEAAIgDAAIgDAAIgEAAQgHAAgEgBQAAABAAADIgBgBIAAAAIAAgCQgDgGgEgDIgCgBIAEgBIADAAIAFAAQADABADgBIADAAIACAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAIAEAAIADAAIAdAAIACABIAWAAIACAAIACAAIAEAAIACAAIADAAIAEABIAFAHQAFAFACAJg");
	this.shape_95.setTransform(101.6,14.6);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#91091E").s().p("AgTAgIgLgJQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAIgFgEIgBgBIgBAAIAAgBIgGgDIAAAAIgBgBIgFgCIgBAAIgCgBIgGgCIgFgCIgDAAIgDAAIgCAAIgJgBQAAgBAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAOgCIAQgGIgDgBIAAgEIAEgIIAEgFQAFgFAEAAIACAAQAHABACAKIANgBIAWAAIA8ABQAEAAABAEIADAKIABABIAAADIABABIACAKIAAAAIABAEQgBADABAGQgBACgEgCIgUAHIgJAAIgNABIgGAAQgEgCgGABQgEABgEgBQgDgBgEABIgPAAIgDgBQABADgEABIgBAAIgCAAg");
	this.shape_96.setTransform(99.4,16.6);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#C9C1B3").s().p("AjUCKIgEgBQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAAAgBAAIgBAAIgCgCIgCgBIgEgCIgBgBIgCgCQgGgDgHgHIgMgNIgWgbQgQgXgFgMIgCgJQAAgDgEgJQgEgLgFgKIgDgKIgPguIgMglIAAgCIAAgBIAAgBIgBAAIAAgCIAAgBIAAgBIgBgBIAAgEIgBgBIgBgFIgBgCIAAgBIAAgBIAAgCIgBgCIAAgBIAAgCIAAgBIgBgDIAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgEIAMgCIgBADQABAJADACQACAEACACQgBAHABABIABAEQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAFAEIABAIQAEADAAACQABACgBADQACAFADACQAGAGgBAGIAAACIAFAIQAEAGgDAEIACAEQgBAFAGACIAAABIAEAFQADADAAADQABADADAEQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIACAHQABAAAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAIACAEQADAEACAFQAAADAEAFIAHAKIAAADQADADgBACQAGAIACAJQABAEACABIAEAFQAAACACAFIAEAJQAFAHAAAIIACAEQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgKgDgIgIIgFgEQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAQACAFAIAGIgCACQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAABAAIAMALIAKAGIACABQAGAGAKACIAJgBQAKgCAUgJIBIgeIARgHIAVgJIAogPIALgFIASgIIA1gUIAOgGIANgFQAJgBAQgIIAKgDIBQgbIAFgBIASgGQAQgFAKgEIAxgQIAJgCIAMgEIAHgCIAOgEIAHgBIAAADQgMAFgGAAIgPAFIiXAyQgdAGgOAHIg9AXIgUAIQgNAGgIACIgNAFIgUAKIgsASIh1AxQgPAGgNACg");
	this.shape_97.setTransform(59.2,49.7);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#BDAEA1").s().p("AjaC4IgHgDIgUgMIgKgKQgCgDACgCQgIgGgBgFQAAgBABAAQAAAAABABQABAAAAAAQABABAAABQAKAIAGADQAFACACAAQgEgPgCgEQgFgJgCgIIgCgEQgDgCgCgHQgBgEgFgIIgEgKQgCgGgEgEQgEgFgCgGQAAgCgCgCIgEgGIgDgGIgCgHQgBgEgCgCIgCgEQgDgJgHgFIgCgCQgEgIACgFQAAgDgDgCQgEgFAAgGQAAgDgFgHQgFgFABgFQAAgCgDgDQgDgCAAgEQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAAAAAQgDgBgBgEIgDgGIgBgEQACgFgGgHQgGgHAFgGIAIgDIAOgDIACgBIAFgBIgBgIQgBgUACgQQABgNAFgNQADgIAGgFQAEgFAIgBQAJAAAHAEQAEACABADIgCAEIgEADIgMAOQgFAGgGgBQgDAGgDACIgBABIgCAIIgCAIIABANQAAAGgDAEQAAABAAAAQAAABAAAAQAAAAAAABQABAAAAABIAAAAQgEAEADAGQACACABAGQABAIAFANIAHARIADAIIAGAQIADAHQACAEACACQADACABAEIAHAMIAHAKQAEAGABAEQACAHAGAFQADADADAIIAKAOQAFAJAFAFQAEAEAEAIIAJAOQADADACAFIACAEQAAABABAAQAAAAABAAQABAAAAAAQABAAABAAQABACgDAEIgJATQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABAAIgEADIgVAIIAEAEQAPALAUgJIAugSIAjgPIAXgJIAWgJIAVgIIAMgFIApgRIA/gXIAygTIBOgbIA4gSIBRgXIAHgBQABACgBADIgEAUIgBABIAAgCIAAgEIABgEIABgEIAAgCQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAABIj4BRIgdAKIhDAbIg8AYIg1AVIg1AWIgbALQgKAEgHAAIgFgBg");
	this.shape_98.setTransform(59.8,44.7);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#E3DED2").s().p("Aj2BYIgCgBIgCgCIgBgEIgBgCIgEgJIgCgCQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQAGgDADACQABABAkgQQASgGAOgFQAMgHAHgBIAugKIAugMIBBgUQBEgWAQgEIANgBQAIAAAEgDIAGgGQADgBAGAAQASgEAsgTIAggMIARgDIAKAAQACgBAAgEQADAEADAJIAEALQAGAKAAAKIgBgBQgEgFgZAGIggAKQgjAMghANIgCACIgOAAIgLAIIgTAGIgUAGIgNABQgGAAgTAHQgQAHgoALIhgAbQg7ARgmAHQgJAFgEAAQgHAAgCgEg");
	this.shape_99.setTransform(136.9,16.3);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#E3DED2").s().p("AjTBzIgEgOIAAADQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAIgCgCIgCABIgBACQgFAFgEgBQgEgCgDADQgHAGgFgGIgCgDIgCgEIAAgCIgEgMIAAgFQACAAAEADIAFAEIAHgEQAEgCACABIAGAAIACgCQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAAgEQgOgpgTgcIgKgMQgGgJgJAFIgHACQgHACgGACIgDAAQgDgCgCgDIgCgDIgCgBIgEgEIgBgCIgBAAIgDgEIgBgEQADgDAGABIATgBQADAAADABIAHAFQgHgGgHgCQgBAAgBAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAHgCIAFAAQALAAALAIQgHgFgHgCQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAQACgCAEABIAjgEIC4gXICVgYIBCgMIBXgRQACgCAGgBIABAAIACAAIABAAIACgBIACAAIABABIAAgBIACABIAGgBIACAAIADABIACAAIAFACIABAAIACABIAFABIACABIAEACIAEACIADACIACABIABABIADACQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQgEACgDgCIgHgDQgEACgNABIgCAAQgIAEgNAAIgCgBQgDgBgCACQgEACgFgCQgDgBgEACQgGAEgHgBQgCgBgDACQgGAEgHgBQgFgBgEADQgDACgDgBQgGAAgHACIgCABQgEgCgFACIgJAEQgEACgGgCQgDgBgDABIgDACQgDgBgFACIgJADQgMAAgGACIgDAAQgCACgHAAIgOABQgDAAgCACQgDACgDgBQgEAAgEACIgOAEIgMACQgJABgBABQgBAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQgDgCgCACQgDACgKABIgNAEQgDABgCgCQgDgCgDACIgLADIgEAAQgFAAgEAEQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgFgCgHACIgKABQgEABgBACIgCABIgFABIgFAAQgCAAgGACQgCACgDgCQAAgBgBAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQgGACgCADQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgDgBgGAAIgIAAQgEgCgDAFQgCAEgEgCIgEAAQgEABgDgBQAAABAAAAQgBABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAgBgBIgCgBQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAAAIgEAAIgDgCQgDADgKAAQgIgBgEAEIgFADIgCgDQgLACgGgBIgHABIgFACQgDABgDgBQgBACACAEIAQAVQACADAAACQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBgBIgPgTIgGgHIgEgBIgGAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAADADAEQAMAPAPAfQAIAPAEANIAFAIQACADAEgDQAFgDADAEQACgFgCgEQgDgLgIgQQgCgFABgCQACAAACAFIAKAXQACAEACABQAAAAABAAQAAAAABAAQAAAAABAAQABAAABAAIAIABQAEABADgDIALgDIAagFQAHgDACgCQACgDADACQADAEAJgCQAHgCACgFQABAAAAAAQAAAAABAAQAAAAABAAQAAAAAAABQADACADgCQAGgCADADQADgBgBgFQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAFAEAFgDQADgDAKAAIAJgDIAHgBIADgDIAEAAQAHgEAGAFQAEgFAMABQABAAAAAAQABgBAAAAQAAgBAAAAQABgBAAgBQACgBABACIAAgCIAAgCIAJgBIARgBIAHAAQAFAAACgDQABgBAFABQAEgEAKgBIAGgCQADgCADABQAEACAEgEQADgCAEABQAEACABAAIADgEQADgEAGAAQABAAAAABQAAAAAAAAQABAAAAAAQAAgBABAAQAFgDAMgCQADgBAGAAIAMgCIADgBQADgBAFAAQAFABAIgGQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABQAGAAADgEQADgEAEACQAEABABgDQADgCAEAAQAAAAABABQABAAAAAAQABAAAAAAQABgBAAAAQAGgDAGAAQAEgGAIACIACgBQAEgFAEAEIAFgEQADgCADACIABgDIABgCIAFgBQADgBACABQAFADAFgDQAIgGAEABQAAAAABAAQAAAAABAAQAAAAABAAQABgBAAAAIAEABQADgDAFgBIAIgCQAEgBAAgEQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAIADgCQAAgEACgDIAAgFQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAABQAAAAAAAAQABAAAAABQABAOgBAHIgCARIgLAMIgBABQgDAAgDADIgFAEIgFADQgDABgDgBIgEABQgDACgGAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBABQgDACgFAAQgFAAgCAAQgEADgGAAQgFAAgDADQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQgMgBgHAHQgDgDgFACIgJADIgJAEIgOAFQgEABgCgBIgHABIgIADIgHADQgEACgEgBQgFABgDgBQAAAAgBAAQAAAAAAAAQgBABgBAAQAAABgBAAQgDAEgCgBQgJgDgFAFIgEgDQgHAHgCABQgHACgFgCQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAAAIgFAAQgEAFgGgBQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABQgEAEgIgCQgFgDgCAEIgBABIgJADQgGABgEgBQgDgBgHAFQgDADgDgCQgEgDgCADQgEAEgEgCQgDADgFAAQAAAAgBAAQAAABAAAAQgBAAAAABQgBAAAAABQgDAEgDgCIgEgBQgLABgIAEQgBAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgGgDgLAHQgEABgCgDQgCAEgFgBQgEAEgFgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgDADgFgCQgGgBgEAFQAAACgEABIgSACQgHACgIAAIgFABQgFAEgDgDIgEACQgEAFgEgCQgDgBgGACQgGABgCgGQABAEgCAGQgBAEgFABIgGACIgDABQgDAAgBgEg");
	this.shape_100.setTransform(65.1,28.7);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#91091E").s().p("AjUCiIABgBIgBAAIABgCIACgDIAAgCIAIgdIADgPIADgKIABgGIAAgBIAEgXIAEgUIAJgkIAJgqQABgGADgBQgBAAAAgBQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAIAMAGQAGADAFgDQAEgCAMAGQAOADAOgEQAFgBACABIADACIACAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAIAEgBQADAAABgCQACgCAAgFIABgHQgBgBADgHQACgFAAgIIABgOIACgYIAAgdIAAgOIgBgOIAAgDIgBgCQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQADgBACACQAAAFACAFQABAEADABIAIAEQAFADAAADIACABQAAABABgBIAAABIACACIAAABIADAEIABABIAAABIABABIAAABIABACIABABIABACQADADABAFIABACQABABAAAAQAAABAAAAQAAAAABABQAAAAAAABIAAADIACAFIAAAAIADAIIACAFIAAADIADAIIAFAcIAAADIAAACQAAAAAAABQAAABAAAAQAAABAAAAQAAAAAAABIAAAJIgBAKQgBAGgCAEIgDAIIAsAOIAPAFIACABIACABIABAAIAQAGIABABIACAAIAOAFIADACIACAAIABABIADAAIABABIACABIAJADIACAAIABABIACAAIABABIACABIAGACIADABIABAAIADABIACAAIABABIABAAIADABIAkAKIAQAFIADAAIABABIADAAIABAAIALADIADABQABAAAAAAQAAAAABAAQAAAAAAAAQAAABABAAIgHABQgLADgSADIgdAEIgFABIgBAEIABABIAAACIABACIAAABIAAABIABAEIAAAAIABABIAHAOIABACIgBABIgCgBQgRgDgRgHIgCgBQgDgEgEACIgBAAIgBgCIgBABQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgBgBQgFAAgDgDIgCACIgCgBIAAgBQgHgDgEAAQgBgDgFAAQgGAAgGgEIgGgCIgHgDIgDgBQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgCABgKgEIgGgCQgIgEgFAAIgXgIIAAAAIAAAAIgDgBIgBAAIgBgBIgBAAIgCgBIgBAAIgCgBIgBAAIgCAAIgBAAIgEgCIgBAAIgFgCIgCgBIAAABQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAIgEgCIgZgIIgCALIgBAJIgCALIgBABIgBABQAAABAAAAQAAABAAABQAAAAgBAAQAAABAAAAQAAAAAAABQABAAAAABQgBAAAAABQgBAAAAABQAAAAABABQAAABAAAAQAAABgBAAQAAAAgBABQABAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIABAAIAAACQAAABAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIACABIAAACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAIACACQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAIgBAAQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIACACQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAABABAAQAAABAAAAQABAAAAABQAAAAAAABIgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAABAAABQABAAAAABQgBAAAAABQAAAAgBAAIACABIAAACIgDABIACACIAAABIgDABIADACIAAABIgDABIABADIgDABIgDAFIAAACIAAACIgBABIgCAEIACAEIgEADIgBABIgCADIgDABQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIgDAAIgBgBQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgCgBIgSgPIgPgKIgCAAIgCAAIgLAFQgTAKgJAGIgOAIQgEADgDAAQAAAAAAAAQgBgBAAAAQAAgBABAAQAAgBAAAAg");
	this.shape_101.setTransform(113.7,35.5);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#C9C1B3").s().p("AiMBoQgEgBgCgNQgCgOADgDQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBABIgGABIgDgDQgCgBgKACQgJACgCgFQgHAIgKgBIgIgBQgDAAgEACQgJADgIAAQgLgBgDgIIgDgEIAAgCQgBgGgCgCIAAgDQAAgCgCgDIgBgCIgBgFIgBgBIgBgBIgBgEIABgBQADgBAEAEIAJgBIBGgSIBdgXQBlgeBQgaIASgGIBGgXIAfgLQAXgGAGAIIADAOIACAOIAAABIAAADIABACIgBADIABABIAAAIQAAAHgCAMIAAACIAAACQgCALgHAOQgFAHgGAHIgIAIQAAAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgVAFQgBAAgBABQgBAAAAAAQgBAAAAAAQgBgBAAAAIgEAAIjWA0Ig1AOQgeAHgQADIgBAAIgIABIgIACg");
	this.shape_102.setTransform(137.7,21.4);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#E3DED2").s().p("AjjByIAAgBIgCgCIAAAAIgBgBIgCgEIgBgBIAAAAQAAgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgBIgBAAIAAgBIgGgJIgLgOQgFgGgBgIIAAgDIgBgCIgCgMIAAgBIgBgCIAAgBQgEgPgGgGIgBgCQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAhgIIBjgXIExhcIAUgHQALgDAMADQALADAKAGQAGAEAHAHIAMANQAHAJAKASIADAJQAAADgDACQgFgEgFAFQAAABAAAAQgBAAAAAAQgBAAgBAAQAAAAgBgBIgEABQgBAEgEAAIgHABIgSAGIgDACIgCACQgDAAgDACIgHACQgDAAgCADIgCABIgDABQgEACgHABQgFAAgDACIgDADQgBAAAAAAQAAAAgBAAQAAABgBgBQAAAAgBAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAIgFAAQgKABgCACQgBAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgDgBQgCADgEADIgIAGIgBgCIgBgBIgGAEQgBABAAABQgBAAAAAAQgBAAgBAAQAAAAgBgBQgEgDgDAEIgBABIgOADQgBADgEABIgHABIgDACQgIAHgGgCQgEAAgDADQgFAGgHgDIgCACQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgEgCgEAEIgDgBIgDACQgBACgDABIgHAAQgEAAgCADQgBABgEAAIgEAAQAAAAAAAAQAAABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgDgCQgFAAgHAEQgDACgDAAQgEAAgFADQgFAEgFgEIgCgBIgEAFQgDACgCABIgCgBIgBgCQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAAAABQgEAEgEgDQgEgCgBADQgDAFgHgBQgGAEgIAAIgEACQgDAEgEgDQgFgCgCAEQgDADgCgBIgGACIgRACIgDABQgEACgFAAQgCAEgEgBQgIgCgDAHQgCAEgDgBQgEgDgLAFIgBAAQgEAAgHACIgKADQgJAAgEACg");
	this.shape_103.setTransform(133.7,11.5);

	this.addChild(this.shape_103,this.shape_102,this.shape_101,this.shape_100,this.shape_99,this.shape_98,this.shape_97,this.shape_96,this.shape_95,this.shape_94,this.shape_93,this.shape_92,this.shape_91,this.shape_90,this.shape_89,this.shape_88,this.shape_87,this.shape_86,this.shape_85,this.shape_84,this.shape_83,this.shape_82,this.shape_81,this.shape_80,this.shape_79,this.shape_78,this.shape_77,this.shape_76,this.shape_75,this.shape_74,this.shape_73,this.shape_72,this.shape_71,this.shape_70,this.shape_69,this.shape_68,this.shape_67,this.shape_66,this.shape_65,this.shape_64,this.shape_63,this.shape_62,this.shape_61,this.shape_60,this.shape_59,this.shape_58,this.shape_57,this.shape_56,this.shape_55,this.shape_54,this.shape_53,this.shape_52,this.shape_51,this.shape_50,this.shape_49,this.shape_48,this.shape_47,this.shape_46,this.shape_45,this.shape_44,this.shape_43,this.shape_42,this.shape_41,this.shape_40,this.shape_39,this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.8,0,191.3,745.7);


(lib.column = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.ColumnGuy("synched",0);
	this.instance.setTransform(190,743.6,1,1,0,0,0,190,743.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:5.4,y:743.7},99,cjs.Ease.get(-1)).to({rotation:0.2},50,cjs.Ease.get(-1)).to({rotation:-1.4,y:738.6},11).to({rotation:0.2,y:743.7},10).to({rotation:-4.9,x:193.4,y:728.4},79,cjs.Ease.get(-1)).to({rotation:-0.2,x:192.9,y:742.9},100,cjs.Ease.get(-1)).to({rotation:0.5,x:191.8,y:740.3},10,cjs.Ease.get(-1)).to({rotation:0,x:190,y:743.6},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.8,0,191.3,745.7);


// stage content:



(lib.what = function() {
	this.initialize();

	// text
	this.text = new cjs.Text("WE DO?", "bold 99px 'Roboto Slab'", "#FEFEFE");
	this.text.textAlign = "center";
	this.text.lineHeight = 119;
	this.text.lineWidth = 877;
	this.text.setTransform(1338.6,439.2);

	this.text_1 = new cjs.Text("SO WHAT DO", "bold 99px 'Roboto Slab'", "#FEFEFE");
	this.text_1.textAlign = "center";
	this.text_1.lineHeight = 119;
	this.text_1.lineWidth = 877;
	this.text_1.setTransform(1341.5,311.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#315175").s().p("EgicALHIAA2NMBE5AAAIAAWNg");
	this.shape.setTransform(1348.6,506.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3C6196").s().p("AurNXIAA6tIdXAAIAAatg");
	this.shape_1.setTransform(1586.1,385.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#355490").s().p("EgmnAKhIAA1BMBNPAAAIAAVBg");
	this.shape_2.setTransform(1259.1,384.9);

	// squiggles
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#C2B197").ss(2,0,0,4).p("AAsCcIgOglQgiANgbgIIgBgcQAfAHAagLQAUgIAIgPQAJgOgGgQQgGgPgPgHQgNgGgXAAQgjgBgTgIQgXgHgIgXQgJgXAJgWQAJgWAYgOIgOglIAWgJIAOAkQAcgKAXAEIAAAcQgZgEgYAJQgUAIgGAOQgGAMAFANQAFAOAPAFQAMAFAcABQAiABATAKQAVAJAJAYQAJAXgJAXQgJAYgaAPIAPAmg");
	this.shape_3.setTransform(655.8,907);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAeB3QgiANgbgIIgBgcQAfAHAagLQAUgIAIgPQAJgOgGgQQgGgPgPgHQgNgGgXAAQgjgBgTgIQgXgHgIgXQgJgXAJgWQAJgWAYgOIgOglIAWgJIAOAkQAcgKAXAEIAAAcQgZgEgYAJQgUAIgGAOQgGAMAFANQAFAOAPAFQAMAFAcABQAiABATAKQAVAJAJAYQAJAXgJAXQgJAYgaAPIAPAmIgXAJg");
	this.shape_4.setTransform(655.8,907);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#C2B197").ss(2).p("AA0IaQihA+hBhOQg2g/AEitQABhAAckRQAWjZgNhpQh9gKgvgaQg0geAygwQAOgOAUAFQAIACAfAPQA4AaAqghQArgpAUgSQAlgfAQARQBCBMg9AqQgBAAgyAcQgbAPABANQBAAJCIBmQCeB0BaCCQBwCigoCHQgxClkSBog");
	this.shape_5.setTransform(656.9,900);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E5D0B5").s().p("AiuIKQg2g/AEitQABhAAckRQAWjZgNhpQh9gKgvgaQg0geAygwQAOgOAUAFQAIACAfAPQA4AaAqghQArgpAUgSQAlgfAQARQBCBMg9AqIgzAcQgbAPABANQBAAJCIBmQCeB0BaCCQBwCigoCHQgxClkSBoQhGAcg1AAQhDAAgkgsg");
	this.shape_6.setTransform(656.9,900);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgOCiIABgoQgRgBgQgFQgQgGgLgIIAKgaQAZASAgABQATABANgLQAOgKAAgRQABgQgLgMQgLgLgUgKQgggMgPgOQgRgSABgYQABgZAQgRQARgQAbgEIACgoIAWABIgBAmQAeACAVANIgLAaQgWgOgbgBQgTAAgMAKQgKAJAAAOQgBAPAMAKQAKAJAZANQAfAOAOAOQAOASAAAaQgBAYgQASQgSATgeAEIgBApg");
	this.shape_7.setTransform(625.2,887.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgPCiIACgoQgRgBgRgFQgQgGgKgIIAKgaQAZASAfABQATABAOgLQANgKABgRQAAgQgLgMQgKgLgVgKQgggMgOgOQgRgSAAgYQABgZARgRQAQgQAcgEIABgoIAXABIgBAmQAdACAWANIgLAaQgXgOgbgBQgTAAgLAKQgKAJgBAOQAAAPALAKQAKAJAZANQAfAOAOAOQAPASgBAaQgBAYgQASQgSATgdAEIgCApg");
	this.shape_8.setTransform(625.3,887.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#C2B197").ss(2).p("AhKI3QiMgEhXhjQhVhhABiQQABibBmiSQB0ioDbh5Qhvg6gcgiQghgqA5gmQAyghAWAHQAQAEAJAeQAMApADAFQAOAWAegJQAMgDArgZQAWgMANASQBDBdhAAQQgBAAg3AHQgfAEgFAMQA4AhBYCTQBmCoAgCZQApDDhZBtQhsCFkjgJg");
	this.shape_9.setTransform(618.4,868.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E5D0B5").s().p("AhKI3QiMgFhXhiQhVhhABiQQABibBmiTQB0inDbh5Qhvg7gcghQghgqA5gmQAyghAWAGQAQAFAJAeQAMAoADAGQAOAWAegJQAMgDArgZQAWgMANASQBDBdhAAPIg4AIQgfADgFANQA4AgBYCUQBmCoAgCZQApDChZBtQhlB+kGAAIgkgBg");
	this.shape_10.setTransform(618.4,868.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#C2B197").ss(1,0,0,4).p("AAVChIgJgnQgjAIgagLIAEgcQAdALAcgHQAUgFALgNQAKgOgEgQQgDgQgOgIQgMgIgXgFQgigFgSgJQgVgMgFgYQgGgYAMgVQAMgUAagKIgJgnIAYgGIAJAmQAbgGAYAIIgEAcQgZgJgZAGQgUAFgJANQgHAMADANQADAOAOAIQAMAGAbAFQAhAGASAMQATAMAFAZQAGAYgMAWQgMAXgcALIAJAog");
	this.shape_11.setTransform(568.8,838.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAMB6QgjAHgagKIAEgdQAdALAcgGQAUgFALgNQAKgOgEgQQgDgQgOgIQgMgJgXgEQgigFgSgJQgVgNgFgXQgGgYAMgVQAMgUAagLIgJgnIAYgFIAJAmQAbgGAYAIIgEAcQgZgJgZAGQgUAFgJANQgHALADANQADAPAOAIQAMAGAbAFQAhAGASAMQATAMAFAZQAGAYgMAVQgMAXgcALIAJApIgYAFg");
	this.shape_12.setTransform(568.8,838.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#C2B197").ss(2).p("AgNINQiCgJhYhoQhThigTiUQgTiWA3iLQA8ibCFhiQAUgOgwgSQgjgOgrgHQg9gKgTgQQgUgRA1gEQBHgHAPAOQAOANApgFQAsgGAggjQAagdAlAHQBHAMgWAPQgBAAhHAbQgGADghAJQgXAGgGAGQgRAQBUAsQCMBKBgCfQBbCXAMCgQAMCohTBkQhdBwi7gNg");
	this.shape_13.setTransform(570,833.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#E5D0B5").s().p("AgNINQiCgJhYhoQhThigTiUQgTiWA3iLQA8ibCFhiQAUgOgwgSQgjgOgrgHQg9gKgTgQQgUgRA1gEQBHgHAPAOQAOANApgFQAsgGAggjQAagdAlAHQBHAMgWAPIhIAbQgGADghAJQgXAGgGAGQgRAQBUAsQCMBKBgCfQBbCXAMCgQAMCohTBkQhUBkigAAIgkgBg");
	this.shape_14.setTransform(570,833.4);

	this.instance = new lib.column();
	this.instance.setTransform(738.8,494.9,1,1,0,0,0,97.3,373.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#C2B197").ss(1,0,0,4).p("AAACTIgCgkQggADgXgNIAGgZQAYANAbgDQASgCALgKQALgLgCgQQgBgOgLgJQgKgIgUgHQgegJgPgJQgRgOgCgWQgCgWANgRQANgRAYgGIgEgkIAWgCIACAiQAbgBAUAJIgHAZQgVgKgWACQgTACgKALQgIAJACAMQABAOAMAHQAJAHAYAIQAdAJAPAMQAPAOACAXQACAWgNASQgNATgaAHIADAlg");
	this.shape_15.setTransform(539.7,967.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgCBvQggACgXgMIAGgZQAYANAbgDQASgCALgKQALgMgCgPQgBgOgLgJQgKgJgUgGQgegJgPgKQgRgNgCgWQgCgWANgRQANgRAYgHIgEgjIAWgDIACAjQAbgBAUAJIgHAYQgVgKgWADQgTABgKALQgIAKACAMQABAOAMAHQAJAHAYAIQAdAJAPAMQAPANACAYQACAWgNARQgNAUgaAGIADAlIgWADg");
	this.shape_16.setTransform(539.7,967.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#C2B197").ss(2).p("AhJH3Qh7AMhMhZQhHhTgHiMQgGiPBBiMQBIicCKhqQhUgfgVgxQgKgZAIgoQAEgUAMAEQAGACAYAUQA5AvAtgLQAegHAvgcQAUgNAXAZQAPAQg3ApQg+AwgEAQQBrAnBsB+QByCEAjCJQApChhXBpQhmB8kHAag");
	this.shape_17.setTransform(541.5,959.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#E5D0B5").s().p("AkQGqQhHhTgHiMQgGiPBBiMQBIicCKhqQhUgfgVgxQgKgZAIgoQAEgUAMAEQAGACAYAUQA5AvAtgLQAegHAvgcQAUgNAXAZQAPAQg3ApQg+AwgEAQQBrAnBsB+QByCEAjCJQApChhXBpQhmB8kHAaIgdABQhnAAhDhOg");
	this.shape_18.setTransform(541.5,959.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#C2B197").ss(1,0,0,4).p("AhVCIIATgjQgggSgNgaIAVgTQANAaAdAQQATAKAQgDQAPgEAIgPQAHgOgEgPQgEgPgOgTQgXgYgGgUQgIgXAMgWQAMgWAUgHQAXgIAaAJIATgjIAVAMIgSAiQAbAPAMAVIgVATQgPgXgXgNQgSgKgQAFQgMADgHAMQgFANAFAPQADAMATAXQAVAZAFAVQAGAXgMAWQgMAWgXAIQgWAKgcgKIgUAkg");
	this.shape_19.setTransform(313.3,866.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AhVCIIATgjQgggSgNgaIAVgTQANAaAdAQQATAKAQgDQAPgEAIgPQAHgOgEgPQgEgPgOgTQgXgYgGgUQgIgXAMgWQAMgWAUgHQAXgIAaAJIATgjIAVAMIgSAiQAbAPAMAVIgVATQgPgXgXgNQgSgKgQAFQgMADgHAMQgFANAFAPQADAMATAXQAVAZAFAVQAGAXgMAWQgMAWgXAIQgWAKgcgKIgUAkg");
	this.shape_20.setTransform(313.3,866.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#C2B197").ss(2).p("AkcHTQh9gdgMiEQgKh6BWiWQBYiXCMhfQCahrCjAOQAYADgYgtQgSghgbgiQgogwgEgZQgEgaArAgQA7AqABAUQACATAiAXQAlAZAvgGQAngEAZAeQAtA4gZgDQgBAAhHgbQg3gdgOABQgYABAjBZQBACgAJCPQAKCdg5BqQiJD+nJhtg");
	this.shape_21.setTransform(329.2,860.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#E5D0B5").s().p("AkcHTQh9gdgMiEQgKh6BWiWQBYiXCMhfQCahrCjAOQAYADgYgtQgSghgbgiQgogwgEgZQgEgaArAgQA7AqABAUQACATAiAXQAlAZAvgGQAngEAZAeQAtA4gZgDIhIgbQg3gdgOABQgYABAjBZQBACgAJCPQAKCdg5BqQhgCyj8AAQhtAAiJghg");
	this.shape_22.setTransform(329.2,860.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgYByIAFgcQgbgFgPgPIAKgSQARAPAWAEQANACALgGQAKgGACgMQAEgWgdgRQgWgMgJgMQgLgOADgRQADgSAOgLQAOgKASAAIAEgdIASADIgEAcQAUADAPAMIgKASQgPgMgTgDQgPgDgIAHQgIAFgCAKQgBALAHAJQAGAHARALQAVALAIAOQAJAOgDASQgCASgOALQgPANgTAAIgFAdg");
	this.shape_23.setTransform(363.7,848.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgYBzIAFgdQgbgFgPgOIAKgSQARAPAWADQANACALgGQAKgGACgMQAEgVgdgSQgWgMgJgMQgLgOADgRQADgRAOgMQAOgKASAAIAEgdIASADIgEAcQAUADAPAMIgKASQgPgMgTgDQgPgCgIAGQgIAGgCAKQgBAKAHAJQAGAIARALQAVAKAIAOQAJAOgDASQgCASgOAMQgPAMgTAAIgFAdg");
	this.shape_24.setTransform(363.7,848.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("#C2B197").ss(2).p("AhZF1QhggfgwhfQguhbAShuQAThzBUhXQBehiCZgiQhHgqgHgHQgEgEAIgHQAQgLAOgLQA3grACAgQAAAVACACQAFAJAUgLQA7giABAZQABAHgBAVQABATAMAJQAmAdgCAIQgCAFgcgFQhTgPgGAKQBMA5AqCDQApB/gPB8QgSCIhRA9QhfBHieg1g");
	this.shape_25.setTransform(368.4,845.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#E5D0B5").s().p("AhZF1QhggfgwhfQguhbAShuQAThzBUhXQBehiCZgiQhHgqgHgHQgEgEAIgHIAegWQA3grACAgQAAAVACACQAFAJAUgLQA7giABAZIAAAcQABATAMAJQAmAdgCAIQgCAFgcgFQhTgPgGAKQBMA5AqCDQApB/gPB8QgSCIhRA9Qg2AphMAAQg3AAhEgXg");
	this.shape_26.setTransform(368.4,845.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgJCNIAAgjQgggBgVgOIAIgXQAWAPAcAAQAQAAALgKQAMgJAAgPQAAgOgKgKQgJgJgSgIQgdgJgNgNQgPgOAAgWQAAgVAOgPQAOgQAYgDIAAgjIAUAAIAAAhQAXABAVALIgIAXQgTgMgZAAQgQAAgKAKQgIAIAAAMQAAANAKAJQAJAHAWAKQAbALANANQANAPAAAXQAAAVgOAQQgPARgaAEIAAAkg");
	this.shape_27.setTransform(198.8,929.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgKCNIAAgjQgggBgVgOIAIgXQAXAPAbAAQARAAAKgKQAMgJAAgPQAAgOgKgKQgJgJgSgIQgdgJgNgNQgOgOAAgWQAAgVANgPQAPgQAXgDIAAgjIAUAAIAAAhQAXABAWALIgJAXQgSgMgaAAQgQAAgJAKQgJAIAAAMQAAANAKAJQAJAHAWAKQAbALANANQANAPAAAXQAAAVgOAQQgPARgZAEIAAAkg");
	this.shape_28.setTransform(198.9,929.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#C2B197").ss(2).p("AAWG4QiGAnhfhjQhZhcgFidQgFikBgiGQBuibDRg3QgSgOgRAGQgRAKgHAEQgMAHgIgKQgMgNgNgwQgFgTAzAFQA1AGAbAkQALAPAcgRQAngYAOgCQA4gIAPAJQAMAIgWAQQgWAPglALQgqAMglgCQANBAA+CdQA9CZAOBOQAVB/g1BTQhABkiyA0g");
	this.shape_29.setTransform(190.7,920.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#E5D0B5").s().p("AjPF8QhZhcgFidQgFikBgiGQBuibDRg3QgSgOgRAGIgYAOQgMAHgIgKQgMgNgNgwQgFgTAzAFQA1AGAbAkQALAPAcgRQAngYAOgCQA4gIAPAJQAMAIgWAQQgWAPglALQgqAMglgCQANBAA+CdQA9CZAOBOQAVB/g1BTQhABkiyA0QglALgjAAQhZAAhEhHg");
	this.shape_30.setTransform(190.7,920.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgMCiIAAgoQglgBgXgQIAJgbQAZARAgAAQATAAANgLQANgLAAgRQAAgQgLgLQgLgLgUgJQghgLgPgOQgSgRAAgZQAAgYARgRQAQgSAbgEIAAgoIAXAAIAAAmQAcABAXANIgKAaQgXgNgbAAQgTAAgLALQgKAJAAAOQAAAPAMAKQAKAJAZALQAgAMAOAPQAQASAAAZQAAAZgQASQgRAUgeAFIAAApg");
	this.shape_31.setTransform(326,832.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgMCiIAAgoQglgBgXgRIAJgaQAZARAgAAQATAAANgLQANgLAAgRQAAgPgMgMQgKgKgUgKQgigLgPgOQgRgRAAgZQAAgYAQgRQAQgRAcgFIAAgoIAXAAIAAAnQAcAAAXANIgKAaQgXgNgbAAQgTAAgMALQgJAJAAAOQAAAPALAKQALAJAZALQAfANAPAPQAPARAAAaQAAAYgPASQgSAUgdAFIAAApg");
	this.shape_32.setTransform(326,832.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#C2B197").ss(2).p("AgXIEQjVgXhRhpQhIheAoiWQAkiIB4ibQByiVCbh+QgVgQgWAHQgXANgJAFQgQAJgLgLQgPgPgPg3QgCgJASgFQASgGAYACQBDAFAgAqQALAPAxgpQA1gsAVAIQAgAOADASQAEASgVARQgwAmhWgFQBcBdBGCjQBLCpAHCaQAJCwhVBdQhiBsjUgWg");
	this.shape_33.setTransform(319,833.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#E5D0B5").s().p("AgXIEQjVgXhRhoQhIheAoiXQAkiIB4iaQByiWCbh+QgVgPgWAGIggASQgQAJgLgLQgPgPgPg3QgCgIASgGQASgFAYABQBDAFAgArQALAPAxgpQA1gtAVAJQAgANADASQAEASgVARQgwAmhWgFQBcBdBGCjQBLCpAHCaQAJCwhVBdQhRBaihAAQghAAgjgEg");
	this.shape_34.setTransform(319,833.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgPCVIACglQgigCgVgRIAKgYQAWARAeACQARABANgKQANgJAAgQQABgOgKgMQgJgKgTgKQgdgLgNgOQgQgQABgXQACgXAQgPQAPgPAYgDIACglIAWACIgBAjQAaACAUANIgKAYQgVgOgYgBQgSgBgLAKQgJAIgBAMQAAAOAKAKQAJAJAWALQAdAOAMAOQANARgBAXQgBAXgQAQQgRARgbADIgCAmg");
	this.shape_35.setTransform(253.2,833);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgPCUIACgkQgigDgVgQIAKgYQAWAQAeACQARACANgKQANgKAAgPQABgPgKgLQgJgLgTgJQgdgMgNgOQgQgQABgWQACgXAQgPQAPgPAYgDIACglIAWABIgBAkQAaACAUANIgKAYQgVgOgYgBQgSgBgLAKQgJAHgBANQAAAOAKAJQAJAJAWAMQAdAOAMANQANARgBAYQgBAXgQAQQgRARgbADIgCAmg");
	this.shape_36.setTransform(253.2,833);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#C2B197").ss(2).p("ABlmqQAfgEAmgYQARgLAKAAQANABAQATQAkAtgNAMQgGAFgzAFQgnAEgDAGQgDAGAVAhQBUCBAoCXQApCZgUB9QgVCJhaBBQhlBJisgcQiXgYg9hwQg4hmAgiQQAgiKBkh5QBqiACPg1QAVgIgmgcQgbgUgjgSQgXgLgCgPQgBgNAPgLQAkgaAnAcQApAfABALQABAFgJABQgJABgHgEQgIgDAPABQAIAAAJgBg");
	this.shape_37.setTransform(265.2,829.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#E5D0B5").s().p("AhHHcQiXgYg9hwQg4hmAgiQQAgiKBkh5QBqiACPg1QAVgIgmgcQgbgUgjgTQgXgKgCgQQgBgMAPgLQAkgbAnAdQApAfABALIgIABIgCAAIgBAAIAAAAIgDAAIgDAAIgEgBIgBAAIAAAAIgBAAQgHAAAFADIABAAQAGADAIAAIACAAQAIgBAAgFIAAAAQAfgEAmgYQARgLAKAAQANABAQATQAkAtgNAMQgGAFgzAFQgnAEgDAGQgDAGAVAgQBUCCAoCXQApCZgUB9QgVCJhaBBQhJA1hvAAQgpAAgwgIgABNmnIgBAAQgFgDAHAAIABAAIAAAAIABAAIAEABIADAAIADAAIAAAAIABAAIACAAIAIgBIAAAAQAAAFgIABIgCAAQgIAAgGgDg");
	this.shape_38.setTransform(265.2,829.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#C2B197").ss(1,0,0,4).p("AAACSIgBgkQgiADgWgNIAGgZQAZANAagDQASgBALgLQALgLgCgPQgCgbgogMQgegIgPgKQgRgOgCgWQgCgWANgRQANgQAYgHIgEgkIAWgCIACAjQAbgCAUAKIgHAYQgVgKgWACQgTACgKALQgIAJACAMQABAOAMAIQAKAHAXAHQAdAJAPAMQAPAOACAXQACAWgNASQgNATgaAHIADAlg");
	this.shape_39.setTransform(180.1,875.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgBBuQgiADgWgNIAGgZQAZANAagCQASgCALgLQALgLgCgPQgCgagogNQgegIgPgKQgRgOgCgVQgCgWANgSQANgQAYgGIgEgkIAWgCIACAiQAbgCAUAKIgHAYQgVgKgWACQgTACgKALQgIAKACALQABAOAMAIQAKAHAXAHQAdAKAPALQAPAOACAYQACAVgNASQgNATgaAHIADAlIgWACg");
	this.shape_40.setTransform(180.1,875.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#C2B197").ss(2).p("Ag3HuQiQAIhdhfQhXhagJiQQgJiVBOiHQBXiYCqhZQhCgYg0gIQgNgCgCgCQgBgCACgKQAHgkA0gGQAPgCAlgBQAkgDAagGQApgKARgYQAEgGADABQADACAPAQQAPARglAnQgsAwgEAPQBrAnBzCCQB5CHAoCLQAtCjhZBoQhqB7kYARg");
	this.shape_41.setTransform(183.5,868.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#E5D0B5").s().p("AkkGXQhXhagJiQQgJiVBOiHQBXiYCqhZQhCgYg0gIQgNgCgCgCQgBgCACgKQAHgkA0gGQAPgCAlgBQAkgDAagGQApgKARgYQAEgGADABQADACAPAQQAPARglAnQgsAwgEAPQBrAnBzCCQB5CHAoCLQAtCjhZBoQhqB7kYARIgYAAQiAAAhVhXg");
	this.shape_42.setTransform(183.5,868.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgiCeIAGgnQgkgIgVgTIAOgZQAXAVAfAFQASADAPgJQAPgIACgRQADgQgKgNQgIgMgTgNQgfgQgMgQQgPgUAEgYQAEgYATgOQASgPAaAAIAGgoIAZAEIgHAmQAdAGAUAQIgOAYQgVgRgagEQgVgDgLAJQgLAIgCANQgCAPAKALQAJALAXAPQAdAQALATQANATgEAaQgEAYgTAQQgUAQgcAAIgGApg");
	this.shape_43.setTransform(405,878.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgiCeIAHgnQglgIgVgTIAOgZQAXAVAfAFQATADAPgJQAOgIADgRQACgQgKgNQgIgMgTgNQgfgQgMgQQgPgUAEgYQAEgYATgOQASgPAaAAIAGgoIAZAEIgHAmQAdAGAVAQIgPAYQgVgRgZgEQgWgDgKAJQgMAIgBANQgDAPAKALQAJALAXAPQAdAQAMATQAMATgEAaQgEAYgTAQQgTAQgcAAIgHApg");
	this.shape_44.setTransform(405,878.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f().s("#C2B197").ss(2).p("Ah7ICQiEgrhBiCQhAh+AZiXQAZieB0h4QCCiHDTguQhig6gJgJQgGgGALgJQAWgPATgPQAvglASAAQAMAAABAVQABAcACAEQAHANAbgQQAxgcATgBQAOgBACARQAAALgBAcQACAaAQAMQA0AogDALQgCAIgngHQgygLgYgDQgpgGgGANQBoBNA5C0QA5CwgWCrQgXC7hwBTQiCBhjbhIg");
	this.shape_45.setTransform(411.5,875);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#E5D0B5").s().p("Ah7ICQiEgrhBiCQhAh+AZiXQAZieB0h4QCCiHDTguQhig6gJgJQgGgGALgJQAWgPATgPQAvglASAAQAMAAABAVQABAcACAEQAHANAbgQQAxgcATgBQAOgBACARQAAALgBAcQACAaAQAMQA0AogDALQgCAIgngHQgygLgYgDQgpgGgGANQBoBNA5C0QA5CwgWCrQgXC7hwBTQhLA4hoAAQhMAAhegfg");
	this.shape_46.setTransform(411.5,875);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f().s("#C2B197").ss(1,0,0,4).p("AhJCPIAQglQgigPgOgZIATgUQARAZAcANQAUAIAQgFQAPgEAGgQQAGgPgGgPQgFgOgPgRQgZgXgIgTQgKgXAKgWQAKgXAWgJQAUgKAaAHIAQgkIAXAJIgQAkQAaAMAQAVIgTAUQgSgXgXgJQgTgJgPAGQgMAFgEAMQgGAOAHAOQAEAMAUAVQAYAXAHAUQAHAWgKAYQgKAXgWAKQgVALgdgHIgRAmg");
	this.shape_47.setTransform(372.3,803.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AhJCPIAQglQgigPgOgYIATgVQARAZAcANQAUAJAQgGQAPgEAGgQQAGgPgGgOQgFgOgPgSQgZgXgIgTQgKgXAKgWQAKgWAWgKQAUgKAaAHIAQgkIAXAJIgQAkQAaAMAQAVIgTAUQgSgXgXgJQgTgIgPAFQgMAFgEAMQgGAOAHAOQAEANAUAUQAYAXAHAUQAHAWgKAYQgKAXgWALQgVAKgdgHIgRAmg");
	this.shape_48.setTransform(372.3,803.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f().s("#C2B197").ss(2).p("AkEHeQighGAHhlQAHhTB7h5QAuguDTivQCmiMBAhUQixjLCEAAQAUAAALASQAEAGAMAhQAWA6A1AGQAZACA9gBQAwADgBAYQgFBlhJgNQgogLgQgFQgegIgJAKQAoA0AcCpQAgDAgbCbQgiDEh7BFQiWBUkLh1g");
	this.shape_49.setTransform(370.7,793.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#E5D0B5").s().p("AkEHeQighGAHhlQAHhTB7h5QAuguDTivQCmiMBAhUQixjLCEAAQAUAAALASQAEAGAMAhQAWA6A1AGQAZACA9gBQAwADgBAYQgFBlhJgNIg4gQQgegIgJAKQAoA0AcCpQAgDAgbCbQgiDEh7BFQg/AjhTAAQhzAAichEg");
	this.shape_50.setTransform(370.7,793.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f().s("#C2B197").ss(1,0,0,4).p("AAiCfIgMgnQghALgcgJIABgcQAeAJAcgKQAUgHAJgOQAJgOgFgQQgEgPgPgIQgNgHgXgCQgjgCgTgIQgVgKgIgXQgHgYAKgVQAKgWAZgMIgMgmIAXgIIAMAlQAbgIAYAGIgBAcQgagGgYAIQgUAGgHAOQgHAMAEANQAFAOAOAGQANAGAbACQAiADASALQAUAKAIAZQAIAXgKAXQgKAXgbAOIAMAng");
	this.shape_51.setTransform(435.1,971.5);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AAWB4QghALgcgJIABgcQAeAJAcgKQAUgHAJgOQAJgOgFgQQgEgPgPgIQgNgHgXgCQgjgCgTgIQgVgKgIgXQgHgYAKgVQAKgWAZgMIgMgmIAXgIIAMAlQAbgIAYAGIgBAcQgagGgYAIQgUAGgHAOQgHAMAEANQAFAOAOAGQANAGAbACQAiADASALQAUAKAIAZQAIAXgKAXQgKAXgbAOIAMAnIgYAIg");
	this.shape_52.setTransform(435.1,971.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f().s("#C2B197").ss(2).p("AAyITQiCAphrhLQhmhHgoiTQgriZAsipQAwi+CQigQh9gKgYgHQgRgGAAgOQgBgNAQghQAbg3ARgLQAOgIAQAPQAbAbAEACQAWAOAdgOQAqgUAKgQQABgCAiAGQA+ANAHARQAGAOgfAVQgQALgrAZQgjAVAAANQB+AXB6B7QB4B6AyCYQA3Cog6CCQhDCXjMBBg");
	this.shape_53.setTransform(431.2,965.5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#E5D0B5").s().p("Ai7HxQhmhHgoiTQgriZAsipQAwi+CQigQh9gKgYgHQgRgGAAgOQgBgNAQghQAbg3ARgLQAOgIAQAPQAbAbAEACQAWAOAdgOQAqgUAKgQQABgCAiAGQA+ANAHARQAGAOgfAVQgQALgrAZQgjAVAAANQB+AXB6B7QB4B6AyCYQA3Cog6CCQhDCXjMBBQgvAPgqAAQhPAAhFgxg");
	this.shape_54.setTransform(431.2,965.5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f().s("#C2B197").ss(1,0,0,4).p("AguCKIAKgjQgggJgRgVIAPgUQATAVAaAHQATAFAMgGQAOgHAEgOQADgOgHgNQgGgMgQgNQgZgRgKgQQgLgTAFgVQAGgWATgLQASgLAXADIAJgjIAVAGIgJAhQAaAIAQAQIgPAVQgSgSgWgGQgTgFgMAHQgJAGgDAMQgDANAHALQAHALATAQQAZAQAIASQAJATgGAWQgGAWgSAMQgTANgZgDIgKAkg");
	this.shape_55.setTransform(422.9,845.6);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AguCKIAKgjQgggJgRgVIAPgVQATAWAaAHQATAFAMgHQAOgGAEgPQADgNgHgNQgGgMgQgOQgZgQgKgRQgLgSAFgWQAGgVATgLQASgLAXACIAJgiIAVAFIgJAiQAaAIAQAQIgPAVQgSgSgWgGQgTgFgMAHQgJAGgDALQgDANAHAMQAHAKATAQQAZARAIASQAJATgGAWQgGAWgSALQgTANgZgCIgKAkg");
	this.shape_56.setTransform(422.9,845.6);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f().s("#C2B197").ss(2).p("Ai2HaQh9gagkiLQghiAA1ifQA1ihBuhhQB9htCRAbQhEg7gBhHQgBgZAIgOQAHgOAGAKQAeA3AQAiQAHAIArARQAZAJA/gWQAygRAMAdQAIAUhCATQhNAWgJAOQBYBMA6CVQA8CcgPCKQgSCfh3BHQiMBTkDg3g");
	this.shape_57.setTransform(418.9,839.4);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#E5D0B5").s().p("Ai2HaQh9gagkiLQghiAA1ifQA1ihBuhhQB9htCRAbQhEg7gBhHQgBgZAIgOQAHgOAGAKQAeA3AQAiQAHAIArARQAZAJA/gWQAygRAMAdQAIAUhCATQhNAWgJAOQBYBMA6CVQA8CcgPCKQgSCfh3BHQhVAyiAAAQhTAAhngWg");
	this.shape_58.setTransform(418.9,839.4);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f().s("#C2B197").ss(1,0,0,4).p("AhJCPIAQglQghgPgPgZIATgUQASAaAcAMQATAIAQgEQAOgFAHgQQAGgOgFgPQgGgOgPgSQgZgXgIgTQgKgXAKgWQAKgXAWgJQAUgKAaAHIAQgkIAXAJIgPAkQAZAMAQAVIgTAUQgQgWgZgKQgTgJgPAGQgMAFgEAMQgGAOAHAOQAEAMAUAVQAYAXAHAUQAHAWgKAYQgKAXgWAKQgVALgdgHIgRAmg");
	this.shape_59.setTransform(427,817.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AhJCPIAQgkQghgPgPgaIATgUQASAbAcALQATAJAQgFQAOgFAHgPQAGgPgFgPQgGgOgPgSQgZgXgIgTQgKgWAKgWQAKgYAWgJQAUgKAaAHIAQgkIAXAJIgPAkQAZAMAQAVIgTAUQgQgVgZgLQgTgIgPAGQgMAEgEANQgGANAHAOQAEAMAUAWQAYAWAHAVQAHAVgKAZQgKAWgWAKQgVALgdgGIgRAlg");
	this.shape_60.setTransform(427,817.2);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f().s("#C2B197").ss(2).p("AjgHhQiBg4gsh8Qgrh5A2iGQA6iNCXhkQCphxD4gfQhUhggNgqQgQgzBEgOQA6gMAUAOQAOALgDAeQgEArABAGQAEAZAgADQALACAygHQAZgEAGAWQAbBvhBgJQgBAAg1gOQgfgIgJAKQAoAzAcCpQAgDAgbCcQgiDEh7BFQiWBTkLh0g");
	this.shape_61.setTransform(419.3,805.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#E5D0B5").s().p("AjgHhQiBg4gsh8Qgrh5A2iGQA6iNCXhkQCphxD4gfQhUhggNgqQgQgzBEgOQA6gMAUAOQAOALgDAeQgEArABAGQAEAZAgADQALACAygHQAZgEAGAWQAbBvhBgJIg2gOQgfgIgJAKQAoAzAcCpQAgDAgbCcQgiDEh7BFQg/AjhTAAQhyAAidhEg");
	this.shape_62.setTransform(419.3,805.8);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgnCMIAIgjQgigJgQgSIAOgWQASAUAdAGQASAEAMgHQANgHADgPQAEgOgIgMQgHgLgRgNQgagQgLgPQgMgSAFgWQAFgWARgMQASgMAXACIAHgkIAWAFIgHAiQAZAHARAPIgOAVQgQgQgZgFQgSgEgKAHQgLAHgCAMQgDANAIALQAIAKATAPQAaAPAJARQAKATgFAWQgEAWgSANQgTAOgZgCIgIAlg");
	this.shape_63.setTransform(450.6,935.9);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgmCMIAIgjQgjgJgPgSIANgWQASAUAdAGQASAEAMgHQAOgHACgPQAEgOgIgMQgHgLgQgNQgbgQgKgPQgMgSAEgWQAFgWARgMQASgMAXACIAIgkIAVAFIgHAiQAaAHAQAPIgNAVQgRgQgZgFQgSgEgKAHQgLAHgCAMQgDANAJALQAHAKATAPQAaAPAKARQAKATgFAWQgFAWgSANQgSAOgagCIgIAlg");
	this.shape_64.setTransform(450.6,935.9);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f().s("#C2B197").ss(2).p("AilHkQh4gaguhsQgqhlAliHQAliIBqhzQB0h/Cig7QhHg3gEg1QgDgbAUgjQAKgTAKAIQAGAEARAbQAnA+AvADQAeADA3gNQAYgFAOAeQAJAUhCAWQhLAagIAPQBbBGBBCZQBECfgJCPQgLClhyBKQiHBXkDg5g");
	this.shape_65.setTransform(449.3,925.9);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#E5D0B5").s().p("AilHkQh4gaguhsQgqhlAliHQAliIBqhzQB0h/Cig7QhHg3gEg1QgDgbAUgjQAKgTAKAIQAGAEARAbQAnA+AvADQAeADA3gNQAYgFAOAeQAJAUhCAWQhLAagIAPQBbBGBBCZQBECfgJCPQgLClhyBKQhSA1iAAAQhRAAhngXg");
	this.shape_66.setTransform(449.3,925.9);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgyBZIALgXQgUgLgKgQIANgNQAKARASAJQAMAGALgDQAIgCAFgKQAIgRgSgXQgQgOgEgMQgFgPAGgOQAHgOAOgGQAMgFARAFIALgXIAPAHIgLAWQAQAIAJAOIgMAMQgKgOgPgHQgMgGgKADQgIADgCAIQgEAIAEAJQABAIANAOQAOAOAEAOQAEAOgHAPQgHAOgPAGQgNAHgSgGIgMAYg");
	this.shape_67.setTransform(213.5,832.2);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgxBZIALgXQgVgLgKgQIAOgMQAKAQARAKQAMAFALgCQAJgDAEgKQAJgQgTgYQgQgOgEgMQgFgPAHgOQAGgOAOgFQAMgGASAFIALgXIAOAHIgLAWQAQAIAKAPIgNALQgKgNgPgIQgMgGgKADQgIAEgCAHQgEAJAEAIQABAJANAOQAOAOAEANQAEAPgHAOQgHAOgPAHQgNAGgSgFIgMAXg");
	this.shape_68.setTransform(213.5,832.2);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f().s("#C2B197").ss(2).p("Ai0ErQhTgigHhmQgGhdA5hnQA6hqBag1QBig8BkAmQgogyAIgyQADgRAHgJQAHgJADAIQAOAqAHAaQADAHAcARQARAKAvgHQAkgGAFAWQADAPgxAFQg4AFgIAIQAzBAAVBwQAWB0gdBeQghBthcAiQhrAnivhIg");
	this.shape_69.setTransform(218.2,824.7);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#E5D0B5").s().p("Ai0ErQhTgigHhmQgGhdA5hnQA6hqBag1QBig8BkAmQgogyAIgyQADgRAHgJQAHgJADAIQAOAqAHAaQADAHAcARQARAKAvgHQAkgGAFAWQADAPgxAFQg4AFgIAIQAzBAAVBwQAWB0gdBeQghBthcAiQgnAOgvAAQhTAAhxgvg");
	this.shape_70.setTransform(218.2,824.7);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f().s("#C2B197").ss(1,0,0,4).p("AAACSIgBgkQghADgXgNIAGgZQAZANAagCQASgCALgLQALgLgCgPQgCgbgogMQgegIgPgKQgRgOgCgWQgCgWANgRQANgQAYgHIgEgkIAWgCIACAjQAagCAVAKIgHAYQgVgKgWACQgTACgJALQgIAJABAMQABAOAMAIQAKAHAXAIQAdAIAPAMQAPAOACAXQACAWgNASQgNATgaAHIADAlg");
	this.shape_71.setTransform(624.5,966.7);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AgBBuQghADgXgNIAGgYQAZAMAagCQASgCALgLQALgLgCgPQgCgagogNQgegIgPgKQgRgNgCgWQgCgXANgQQANgRAYgHIgEgjIAWgCIACAiQAagCAVAKIgHAYQgVgKgWACQgTACgJALQgIAJABAMQABAOAMAIQAKAHAXAIQAdAIAPAMQAPAOACAYQACAVgNASQgNATgaAHIADAlIgWACg");
	this.shape_72.setTransform(624.5,966.7);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f().s("#C2B197").ss(2).p("Ag3HuQiQAIhdhfQhXhagJiQQgJiUBOiHQBXiZCqhZQhCgYg0gIQgMgCgCgCQgCgCACgKQAHgkA0gGQAPgCAlgBQAkgDAagGQApgKARgYQAEgGADABQADACAPAQQAPARglAnQgsAwgEAPQBrAnBzCCQB5CHAoCLQAtCjhZBoQhqB7kYARg");
	this.shape_73.setTransform(628,959.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#E5D0B5").s().p("AkkGXQhXhagJiQQgJiUBOiHQBXiZCqhZQhCgYg0gIQgMgCgCgCQgCgCACgKQAHgkA0gGQAPgCAlgBQAkgDAagGQApgKARgYQAEgGADABQADACAPAQQAPARglAnQgsAwgEAPQBrAnBzCCQB5CHAoCLQAtCjhZBoQhqB7kYARIgYAAQiAAAhVhXg");
	this.shape_74.setTransform(628,959.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgMCiIAAgoQgRAAgRgFQgQgFgKgHIAJgbQAZARAgAAQATAAANgLQANgKAAgRQAAgQgLgMQgLgKgVgKQgggKgPgPQgSgRAAgYQAAgZAQgRQAQgRAcgFIAAgoIAWAAIAAAnQAdAAAXANIgKAbQgWgOgcAAQgTAAgLALQgKAKAAANQAAAPAMAKQAKAJAZALQAgANAOAPQAQARAAAaQAAAYgQATQgRATgeAFIAAApg");
	this.shape_75.setTransform(493.2,840.6);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgMCiIAAgoQgRgBgRgEQgQgFgKgIIAJgaQAZARAgAAQATAAANgLQANgKAAgRQAAgQgMgMQgKgLgVgJQghgLgPgOQgRgRAAgYQAAgZAQgRQAQgSAcgEIAAgoIAWAAIAAAnQAcAAAXANIgKAaQgVgNgcAAQgTAAgMALQgJAKAAANQAAAPALAKQALAJAZALQAfAMAPAQQAPARAAAZQABAZgRASQgRAUgdAFIAAApg");
	this.shape_76.setTransform(493.2,840.6);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f().s("#C2B197").ss(2).p("AhRI1QiKAAhPhoQhMhjAFiYQAGieBdiUQBoioC3htQgmgThJgRQhQgSgPgGQgjgOAPgWQARgaBZguQA2gbAYAFQARADAIAZQAJAlACAEQANAUAfgFQAfgEA1gTQAUgHAhASQA6AfgGAUQgEAQguAMQg6AMgaAHQguALgEANQA5AfBdCQQBqCmAlCXQAvDBhWBwQhoCJkjAAg");
	this.shape_77.setTransform(494.7,830.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#E5D0B5").s().p("AkqHNQhMhjAFiYQAGieBdiUQBoioC3htQgmgThJgRQhQgSgPgGQgjgOAPgWQARgaBZguQA2gbAYAFQARADAIAZQAJAlACAEQANAUAfgFQAfgEA1gTQAUgHAhASQA6AfgGAUQgEAQguAMIhUATQguALgEANQA5AfBdCQQBqCmAlCXQAvDBhWBwQhoCJkjAAQiKAAhPhog");
	this.shape_78.setTransform(494.7,830.1);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgMCiIAAgoQglgBgXgQIAJgbQAZARAgAAQATAAANgLQANgLAAgQQAAgQgLgMQgLgLgUgIQghgLgPgPQgSgRAAgYQAAgZARgRQAQgRAbgFIAAgoIAXAAIAAAnQAdAAAWANIgKAbQgXgOgbAAQgTAAgLALQgKAJAAAOQAAAPAMAKQAKAJAZALQAgANAOAPQAQARAAAZQAAAZgQATQgRATgeAFIAAApg");
	this.shape_79.setTransform(282.5,921.3);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AgMCiIAAgoQglgBgXgQIAJgbQAZARAgAAQATAAANgLQANgKAAgSQAAgPgMgMQgKgKgVgKQgggLgQgOQgRgRAAgYQAAgZARgRQAPgSAcgEIAAgoIAWAAIAAAmQAeABAWAOIgKAaQgXgOgbAAQgTAAgLALQgKAKAAANQAAAPALAKQALAJAZALQAfANAPAOQAPASAAAZQABAZgRATQgQATgeAFIAAApg");
	this.shape_80.setTransform(282.5,921.3);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f().s("#C2B197").ss(2).p("AgVIXQiKAAhPhnQhMhjAGiZQAGieBciUQBoinC4htQgUgQgUgDQgUgBgIgCQgYgIgZhfQgGgUA4AhQA7AiAhAsQALAPAigoQAogxAVgCQAkgEAJASQAIARgRAZQgRAZgfAQQgkATgogDQANBGBMDRQBJDIASBpQAcCjg/BVQhMBmjTAAg");
	this.shape_81.setTransform(265.2,912.5);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#E5D0B5").s().p("AjuGwQhMhjAGiZQAGieBciUQBoinC4htQgUgQgUgDQgUgBgIgCQgYgIgZhfQgGgUA4AhQA7AiAhAsQALAPAigoQAogxAVgCQAkgEAJASQAIARgRAZQgRAZgfAQQgkATgogDQANBGBMDRQBJDIASBpQAcCjg/BVQhMBmjTAAQiKAAhPhng");
	this.shape_82.setTransform(265.2,912.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f().s("#C2B197").ss(1,0,0,4).p("AgsCbIAIgnQgjgIgUgWIAPgYQAWAWAeAHQAVAFANgIQAPgIAEgQQAHgdgmgbQgdgSgMgRQgNgUAFgYQAGgZATgNQAUgNAaACIAJgnIAYAFIgJAmQAdAHASASIgPAXQgUgSgagGQgVgFgLAIQgLAHgEANQgDAPAJAMQAIALAWARQAcASALATQALAVgGAZQgFAYgUAOQgVAPgcgCIgJApg");
	this.shape_83.setTransform(359.1,978);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgsCbIAIgnQgigJgVgVIAQgZQAVAXAfAHQAUAEANgHQAPgIAEgRQAHgcgmgcQgdgRgLgSQgOgUAGgYQAFgYATgNQAVgNAZACIAJgoIAYAGIgJAlQAdAIATASIgQAWQgUgSgagFQgUgGgMAJQgLAHgEANQgDAPAJAMQAJALAWARQAcASAKATQALAVgFAZQgGAYgTANQgWAQgcgCIgJAog");
	this.shape_84.setTransform(359.1,978.1);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f().s("#C2B197").ss(2).p("AiJIZQiIgfhDhyQhAhvAdiNQAfiWCBh+QCRiODuhMQhjhQgVgmQgZgvBAgaQA3gXAWALQAQAHACAfQAEAqADAHQAIAXAggCQAMgBAvgQQAYgIAKAUQAvBohBAEQgCAAg2gEQgggCgHALQAwArA7ChQBDC3ACCdQADDHhtBbQiEBtkchBg");
	this.shape_85.setTransform(349.9,966);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#E5D0B5").s().p("AiJIZQiIgfhDhyQhAhvAdiNQAfiWCBh+QCRiODuhMQhjhQgVgmQgZgvBAgaQA3gXAWALQAQAHACAfQAEAqADAHQAIAXAggCQAMgBAvgQQAYgIAKAUQAvBohBAEIg4gEQgggCgHALQAwArA7ChQBDC3ACCdQADDHhtBbQhSBFiQAAQhTAAhrgZg");
	this.shape_86.setTransform(349.9,966);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f().s("#C2B197").ss(1,0,0,4).p("Ag2CKIALgjQgfgLgRgWIAQgUQATAWAaAJQATAGAMgGQAPgGAFgPQAEgOgGgNQgGgMgQgPQgZgSgJgRQgKgUAHgWQAHgWATgKQARgKAaAEIALgjIAWAHIgLAhQAZAJAQASIgRAUQgPgRgYgJQgTgGgNAHQgJAFgEAMQgEANAHAMQAGALATASQAYASAIATQAIAUgHAWQgHAVgUAMQgUAMgZgEIgMAkg");
	this.shape_87.setTransform(109.6,859.9);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("Ag2CKIALgjQgfgLgRgWIAQgUQATAWAaAJQATAGAMgGQAPgGAFgPQAEgOgGgNQgGgMgQgPQgZgSgJgRQgKgUAHgWQAHgWATgKQARgKAaAEIALgjIAWAHIgLAhQAZAJAQASIgRAUQgPgRgYgJQgTgGgNAHQgJAFgEAMQgEANAHAMQAGALATASQAYASAIATQAIAUgHAWQgHAVgUAMQgUAMgZgEIgMAkg");
	this.shape_88.setTransform(109.6,859.9);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f().s("#C2B197").ss(2).p("ADdmMQAfAFAqgOQAUgHAJADQANAEAKAXQAXA1gQAIQgHAEgygJQgngHgEAFQgFAFAMAmQAvCTAACaQgBChg0BzQg4B+hoAoQhyAsihhIQiMg/geh8QgahxBEiCQBDh+CAhaQCGhgCagOQAWgCgdglQgWgcgegZQgUgRADgPQACgNARgGQAsgQAeAmQAgAogCALQgBAGgIgCQgJgCgHgFQgGgGAOAFQAIADAJABg");
	this.shape_89.setTransform(120.9,860.7);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#E5D0B5").s().p("Ai1GuQiMg/geh8QgahxBEiCQBDh+CAhaQCGhgCagOQAWgCgdglQgWgcgegZQgUgRADgPQACgNARgGQAsgQAeAmQAgAogCALQgJgBgIgDQgOgFAGAGQAHAFAJACQAIACABgGQAfAFAqgOQAUgHAJADQANAEAKAXQAXA1gQAIQgHAEgygJQgngHgEAFQgFAFAMAmQAvCTAACaQgBChg0BzQg4B+hoAoQgsARgyAAQhSAAhjgtg");
	this.shape_90.setTransform(120.9,860.7);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f().s("#C2B197").ss(1,0,0,4).p("Ag2CKIALgjQgggLgQgWIAQgVQASAWAbAKQATAGAMgGQAPgGAFgPQAEgOgGgNQgGgMgQgPQgZgTgJgRQgKgUAHgVQAHgVATgLQASgKAZAEIALgjIAWAHIgLAhQAZAJAQASIgQAUQgSgTgWgHQgTgGgNAHQgJAFgEAMQgEANAHAMQAGALATASQAYASAIATQAIATgHAXQgHAVgUAMQgUAMgZgEIgMAkg");
	this.shape_91.setTransform(456.1,780.9);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("Ag2CKIALgjQgggLgQgWIAQgVQASAWAbAKQATAGAMgGQAPgGAFgPQAEgOgGgNQgGgMgQgPQgZgTgJgRQgKgUAHgVQAHgVATgLQASgKAZAEIALgjIAWAHIgLAhQAZAJAQASIgQAUQgSgTgWgHQgTgGgNAHQgJAFgEAMQgEANAHAMQAGALATASQAYASAIATQAIATgHAXQgHAVgUAMQgUAMgZgEIgMAkg");
	this.shape_92.setTransform(456.1,780.9);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f().s("#C2B197").ss(2).p("ADdmMQAfAFAqgOQATgHAKADQANAEAKAXQAXA1gQAIQgIAEgxgJQgngHgFAFQgEAFAMAmQAvCTgBCaQgBChgzBzQg5B+hnAoQhzAsighIQiMg/geh8QgbhxBEiCQBDh+CAhaQCHhgCZgOQAXgCgdglQgXgcgegZQgTgRACgPQADgNARgGQAsgQAeAmQAgAogCALQgBAGgJgCQgJgCgGgFQgHgGAPAFQAIADAJABg");
	this.shape_93.setTransform(467.5,781.7);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#E5D0B5").s().p("Ai1GuQiMg/geh8QgbhxBEiCQBDh+CAhaQCHhgCZgOQAXgCgdglQgXgcgegZQgTgRACgPQADgNARgGQAsgQAeAmQAgAogCALQgJgBgIgDQgPgFAHAGQAGAFAJACQAJACABgGQAfAFAqgOQATgHAKADQANAEAKAXQAXA1gQAIQgIAEgxgJQgngHgFAFQgEAFAMAmQAvCTgBCaQgBChgzBzQg5B+hnAoQgtARgxAAQhSAAhjgtg");
	this.shape_94.setTransform(467.5,781.7);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f().s("#C2B197").ss(2,0,0,4).p("Ag2CKIALgjQgfgLgRgWIAQgUQATAXAaAIQATAGAMgGQAPgGAFgPQAEgOgGgNQgGgMgQgPQgZgSgJgRQgKgUAHgWQAHgWATgKQARgKAaAEIALgjIAWAHIgLAhQAZAJAQASIgQAUQgRgSgXgIQgTgGgNAHQgJAFgEAMQgEANAHAMQAGALATASQAYASAIATQAIAUgHAWQgHAWgUALQgUAMgZgEIgMAkg");
	this.shape_95.setTransform(519.1,904.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("Ag2CKIALgjQgfgLgRgWIAQgUQATAXAaAIQATAGAMgGQAPgGAFgPQAEgOgGgNQgGgMgQgPQgZgSgJgRQgKgUAHgWQAHgWATgKQARgKAaAEIALgjIAWAHIgLAhQAZAJAQASIgQAUQgRgSgXgIQgTgGgNAHQgJAFgEAMQgEANAHAMQAGALATASQAYASAIATQAIAUgHAWQgHAWgUALQgUAMgZgEIgMAkg");
	this.shape_96.setTransform(519.1,904.5);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f().s("#C2B197").ss(2).p("ADdmMQAfAFAqgOQATgHAJADQAOAEAJAXQAYA2gQAHQgHAEgygJQgngHgFAFQgEAFAMAmQAvCTgBCaQgBChgzBzQg5B+hnAoQhzAsighIQiMg/geh8QgbhxBEiCQBDh+CAhaQCHhgCZgOQAXgCgeglQgWgcgegZQgTgRACgPQACgNASgGQAsgQAeAmQAgAogCALQgBAGgJgCQgJgCgGgFQgHgGAPAFQAIADAJABg");
	this.shape_97.setTransform(530.4,905.3);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#E5D0B5").s().p("Ai1GuQiMg/geh8QgbhxBEiCQBDh+CAhaQCHhgCZgOQAXgCgeglQgWgcgegZQgTgRACgPQACgNASgGQAsgQAeAmQAgAogCALQgJgBgIgDQgPgFAHAGQAGAFAJACQAJACABgGQAfAFAqgOQATgHAJADQAOAEAJAXQAYA2gQAHQgHAEgygJQgngHgFAFQgEAFAMAmQAvCTgBCaQgBChgzBzQg5B+hnAoQgtARgxAAQhSAAhjgtg");
	this.shape_98.setTransform(530.4,905.3);

	this.instance_1 = new lib.Path();
	this.instance_1.setTransform(444.4,910.2,1,1,0,0,0,397.8,83.9);
	this.instance_1.alpha = 0.422;

	// Layer 9
	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#C8DDE0").s().p("EiV+AXEMAAAgsWIZjDPQVohzWAhxUAsCgDiAB/AALUACBAALAyzABKQZbAlZAAiMBRYgCcMAAKAwrQkugSlZgQQqwghjNAGUgDMAAGg1KgA+Mg0hgA/MhxoAEGg");
	this.shape_99.setTransform(959,421.1);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#B5C6CB").s().p("EiV+gP0MApZAB/UADuAAMBCRgDIUBEugDQAEtgAEUAIRgAHAqQABTUApyABRAFYAAfQETAYG9hoQDegzCng5MAAKAlIMkr9ADDg");
	this.shape_100.setTransform(959,655.3);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#666E74").s().p("EiWsAbFMAAAgzMMAw2gC9MDe9ACUIdliUMAAAA2Jg");
	this.shape_101.setTransform(955.5,906.6);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#BDDDE6").s().p("EiV+ga3MErzAAAMAAKAwqMkr9AFEg");
	this.shape_102.setTransform(959,172);

	this.addChild(this.shape_102,this.shape_101,this.shape_100,this.shape_99,this.instance_1,this.shape_98,this.shape_97,this.shape_96,this.shape_95,this.shape_94,this.shape_93,this.shape_92,this.shape_91,this.shape_90,this.shape_89,this.shape_88,this.shape_87,this.shape_86,this.shape_85,this.shape_84,this.shape_83,this.shape_82,this.shape_81,this.shape_80,this.shape_79,this.shape_78,this.shape_77,this.shape_76,this.shape_75,this.shape_74,this.shape_73,this.shape_72,this.shape_71,this.shape_70,this.shape_69,this.shape_68,this.shape_67,this.shape_66,this.shape_65,this.shape_64,this.shape_63,this.shape_62,this.shape_61,this.shape_60,this.shape_59,this.shape_58,this.shape_57,this.shape_56,this.shape_55,this.shape_54,this.shape_53,this.shape_52,this.shape_51,this.shape_50,this.shape_49,this.shape_48,this.shape_47,this.shape_46,this.shape_45,this.shape_44,this.shape_43,this.shape_42,this.shape_41,this.shape_40,this.shape_39,this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.instance,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape,this.text_1,this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(951,540,1929,1080);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;